### ISSUE TITLE
Function execution log gets overwritten with exception string from handling output parameter

### ISSUE THREAD

**Issue by fashaikh** [Azure/azure-webjobs-sdk#1097]
Please provide a succinct description of the issue.
If function fails to write to output binding, only the binding error is visible in logs. Previous function execution logs get overwritten. 
Seeing #969 again. Also similar to #490 . 
Can share the live repro app. 

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A Create a function with TraceWriter and Bind to an ICollector . 
2. Step B log to the TraceWriter and present some malformed data to the ICollector.  
3. Step B execute the function

#### Expected behavior

Previously emitted logs in the execution should be maintained. Note in this case, I dont know if the input was bad. or if it was some flakiness in writing the output data.

#### Actual behavior

Only the binding  exception is present. 

```
Error while handling parameter sendEmailBatch after function returned:
...Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Tables.TableEntityWriter`1.<FlushPartitionAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Tables.TableEntityWriter`1.<FlushAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
      --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
      --- End of inner exception stack trace ---
```

#### Known workarounds

None
#### Related information 

Provide any related information 

* Package version 
* Links to source Here is a sample:
```javascript
public static async Task<object> Run(HttpRequestMessage req, ICollector<SendEmailBatch> sendEmailBatch, TraceWriter log)
{
    log.Info($"C# HTTP trigger function processed a request. RequestUri={req.RequestUri}");
....     
     /// If this throws an error when handling after the previous execution completes, the previous log is not captured by the sdk
sendEmailBatch.Add(input);

 return "";
 

}
```

**Comment by christopheranderson** [comment]
This will be changed when the App Insights stuff starts to take precedence, so we're going to backlog this for a bit.
