### ISSUE TITLE
Validate App Insights configuration parameters

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk#1126]
So I tried updating my function apps to the latest bits and I got into a real busted state. I was not able to figure it out until I looked at the system logs, because the host was not writing any logs to the file system. This stack trace shows the issue:

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: value
   at Microsoft.Azure.WebJobs.Host.FunctionResultAggregatorConfiguration.set_FlushTimeout(TimeSpan value)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ApplyLoggerConfig(JObject configJson,ScriptHostConfiguration scriptConfig)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ApplyConfiguration(JObject config,ScriptHostConfiguration scriptConfig)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize()
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager)
```
The problem was this host.json file:
```
{
  "id": "764ef545783645918207a0c88b1fc558",
  "functions": [ "Splitter" ],
  "logger": {
    "categoryFilter": {
      "defaultLevel": "Information"
    },
    "aggregator": {
      "batchSize": 1000,
      "flushTimeout": "00:30:00"
    }
  }
}
```

So the problem was that I was using a bad app insights configuration. But this should have been caught and logged correctly.

**Comment by brettsam** [comment]
@paulbatum -- I just tried this and that log *was* written to my host logs on the file system. I also got a red popup in the portal. I've also submitted a PR to improve the error messages (https://github.com/Azure/azure-webjobs-sdk/pull/1212).

When you get a chance, can you double-check that this writes to your file system as well? 

We do *not* currently log this to App Insights, but I should be able to get that working.

**Comment by brettsam** [comment]
Two changes have gone in that should help this.
