### ISSUE TITLE
QueueTrigger binding issue with connection string

### ISSUE THREAD

**Issue by darewreck54** [Azure/azure-webjobs-sdk#1430]
I'm not sure if this is a bug or how my code is setup.  I'm having a lot of issues trying to configure a queueTrigger with a different connection string then the one configured by the webjob.

```
  static void Main(string[] args)
        {
            IServiceCollection serviceCollection = new ServiceCollection();
            ConfigureServices(serviceCollection);

            var configuration = new JobHostConfiguration();
            configuration.DashboardConnectionString = "<connectionString1>";
            configuration.StorageConnectionString = "<connectionString2>";
            configuration.Queues.MaxPollingInterval = TimeSpan.FromSeconds(10);
            configuration.Queues.BatchSize = 1;
            configuration.JobActivator = new CustomJobActivator(serviceCollection.BuildServiceProvider());
            configuration.UseTimers();

          
            // The connection string is read from App.config
            JobHost host = new JobHost(configuration);
            host.RunAndBlock();
        }

   class CustomJobActivator : IJobActivator
    {
        private readonly IServiceProvider _service;
        public CustomJobActivator(IServiceProvider service)
        {
            _service = service;
        }

        public T CreateInstance<T>()
        {
            var service = _service.GetService<T>();
            return service;
        }
    }

 public class WebJobMethods
    {
        public WebJobMethods()
        {
        }
  
        public async static Task ProcessQueueMessageAsync([QueueTrigger(queueName: "<queueName>", Connection = "<connectionString3>")] string logMessage, TextWriter logger)
        {
            await logger.WriteLineAsync(logMessage);
        }
    }


```

I keep getting an error stating:

Error indexing method 'WebJobMethods.ProcessQueueMessageAsync'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'WebJobMethods.ProcessQueueMessageAsync' ---> System.InvalidOperationException : Microsoft Azure WebJobs SDK '<connection3>' connection string is missing or empty. The Microsoft Azure Storage account connection string can be set in the following ways:
1. Set the connection string named '<connection3>'  in the connectionStrings section of the .config file in the following format <add name='<connection3>'  connectionString="DefaultEndpointsProtocol=http|https;AccountName=NAME;AccountKey=KEY" />, or
2. Set the environment variable named '<connection3>'', or
3. Set corresponding property of JobHostConfiguration.
   at Microsoft.Azure.WebJobs.Host.Executors.StorageAccountProviderExtensions.ValidateStorageAccount(IStorageAccount account,String connectionStringName)
   at async Microsoft.Azure.WebJobs.Host.Executors.StorageAccountProviderExtensions.GetStorageAccountAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.StorageAccountProviderExtensions.GetStorageAccountAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Queues.Triggers.QueueTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken)
   End of inner exception
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken)

I'm also using the following dependencies:

    ```
<PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0" />
```

I followed the examples in the test.  https://github.com/Azure/azure-webjobs-sdk/blob/dev/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/MultipleStorageAccountsEndToEndTests.cs

```
  public static void QueueToQueue_DifferentAccounts_SecondaryToPrimary(
            [QueueTrigger(Input, Connection = Secondary)] string input,
            [Queue(Output)] out string output)
        {
            output = input;
        }
```
And still it didn't work.  

Any idea on what the issue is?
Thanks,
Derek

**Comment by darewreck54** [comment]
The stable version 2.0.0 doesn't have the connection parameter for QueueTriggerAttribute.  But I did test it with the newest version 2.1 - 3.0.0 with ASP.net and it doesn't work as well.  

In some config.UserDevelopmentSettings is completely broken so I have to set it directly.

**Comment by paulbatum** [comment]
Just double checking, when you are doing this:
`[QueueTrigger(Input, Connection = Secondary)] string input,` the value 'Secondary' here is the NAME of the connection string specified in your app settings that you want to use, right?

**Comment by Specials** [comment]
I have a similar issue! Not able to use other connection string than the one put in job host configuration for a Blob. Storage account used i GP v1.

In Program.cs I use the **AzureWebJobsStorage** connection string: 
```csharp
var config = new JobHostConfiguration(ConfigurationManager.AppSettings["AzureWebJobsStorage"]);
```

In Functions.cs I use the **Events-EUWEST** connection string:
```csharp
private const string eventQueueConnString = "Events-EUWEST";

public static async Task ProcessEventQueueMessage(
[QueueTrigger(StorageSettings.Event.QueueEventsReference, Connection = eventQueueConnString)] QueueWrapper message,
[Blob(StorageSettings.Event.BlobQueueEventsReference + " /{BlobReference}", FileAccess.Read, Connection = eventQueueConnString)] Stream blobStream,
TextWriter log)
```

In app setting I have both:
**AzureWebJobsEvents-EUWEST** and **Events-EUWEST**, none of which gets picked up.

The web job log writes:
[03/29/2019 08:52:34 > b15afe: INFO] Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessEventQueueMessage ---> System.InvalidOperationException: Exception binding parameter 'blobStream' ---> System.FormatException: Invalid container name: blobqueueevents 

The Queue trigger fires as expected, so this uses the correct connection string.

The container **blobqueueevents** DO exist in the **Events-EUWEST** storage but not in the **AzureWebJobsStorage**, so I don't think the Blob uses the connection string property.

The container name SHOULD be valid, right? So I'm reading the error as does not exist!? This has worked for me for a loooong time previous to changing to two connection strings.

Can anyone see what I'm doing wrong here?
