### ISSUE TITLE
ServiceBusTrigger is not firing even if WebJob is running. Some jobs in "Never finished" state

### ISSUE THREAD

**Issue by marconline** [Azure/azure-webjobs-sdk#1526]
Hello, we currently have an app that hosts 11 WebJobs.
One of these fires - through a ServiceBusTrigger - a function that is typically long-running  (i.e. more than 15 minutes).  This ServiceBusTrigger is configured to have 3 max concurrent calls (is it a per-instance setting, right?) and normally runs smoothly.

A note: this WebJob only hosts that function.

During each day it happens that messages on the ServiceBus queue are not dequeued anymore. I checked on Azure portal and the WebJob is in "Running" status. If I stop it and restart it, everything start again normally.

I enabled the Dashboard and what I noticed is that, sometimes, function executions are marked as "Never finished". There is no timeout on the function or, to be precise, I introduced a Timeout attribute with a 4 hours timeout and "ThrowExceptionOnTimeout" = false, but nothing seems changed.

I know that with those information is almost impossible to tell, but why this happens?
Why do a job is marked as "Never finished"? What should I do to give you more informations?

Thanks for your help.
Marco

**Comment by christopheranderson** [comment]
You're right that that isn't a lot of information to debug with. Could you start with sharing the timeperioud, any logs from your WebJob during that time period, and the name of your WebSite (you can use this method to share it anonymously - https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)

**Comment by marconline** [comment]
Hi Christopher and thanks for your reply.

This happened - for example - on the 20 / 21 of January. I don't know where to get this logs: I know they are somewhere on the blob storage whose connection is configured into the settings. Can you help me in getting those logs?

The website is https://edock-services.azurewebsites.net and the WebJob name is Dropship. No need to share it anonymously :-) at least by now.
By the way it seems that I've mitigated it scaling up and out the AppService plan, from 2 Basic B2 to 2 Basic B3. Please consider that this happened as well with 3 Basic B2 instances.

Thanks.
Marco

**Comment by idbates** [comment]
I have a similar issue - after a lengthy run (although at fairly low frequencies) the ServiceBusTrigger  stops firing. Strange thing is that the messages are still invisibly removed from the topic/subscription so it seems to be a case of the message 'processor' retrieving the message and failing to invoke the webjob. I suspected some kind of memory leak in my code but less sure now.

**Comment by rakeshagarwal0292** [comment]
Any solution to this problem?
I am also facing same problem.

**Comment by valentine-palazkov** [comment]
> Any solution to this problem?
> I am also facing same problem.

In my particular case the issue was in connection leakage.

I suggest to ensure that only one instance of HttpClient (it's thread safe) is used for example - I created many clients thus over time everything just stopped working.

**Comment by idbates** [comment]
I upgraded the webjob to run on .NET core 2.2 / Microsoft.Azure.WebJobs 3.0.12 and  Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.6  which seems to have solved the issue. Upgrading involved some breaking changes due to differences in service bus using Microsoft.Azure.ServiceBus assembly rather than Microsoft.ServiceBus. BrokeredMessage is now Message class.

**Comment by rakeshagarwal0292** [comment]
Hello @idbates Tried to upgrade the .net core and related dlls. Do you have any idea about following error:

System.IO.FileLoadException
  HResult=0x8013141A
  Message=Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
  Source=NewsChannelWebJob
  StackTrace:
   at NewsChannelWebJob.Program.<>c.<Main>b__0_0(IWebJobsBuilder b) in E:\NBA\NewsChannelWebJob\Program.cs:line 43
   at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureWebJobs>b__1(HostBuilderContext context, IServiceCollection services) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsHostBuilderExtensions.cs:line 47
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at NewsChannelWebJob.Program.<Main>d__0.MoveNext() in E:\NBA\NewsChannelWebJob\Program.cs:line 73

Inner Exception 1:
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)


Thanks a lot for your help in advance

**Comment by idbates** [comment]
Hi - I think thats because they moved the assembly to a separate nuget package. 
![image](https://user-images.githubusercontent.com/7227960/65421186-0c09a800-ddfb-11e9-96f6-3e40e4385853.png) did you add a refence to Microsoft.Azure.WebJobs.Extensions.ServiceBus as yet?

**Comment by rakeshagarwal0292** [comment]
Thanks @idbates Now it's working.
I am trying to see if the actual issue still persist.

**Comment by rakeshagarwal0292** [comment]
ServiceBusTrigger problem still there. Many time it just keeps waiting.

**Comment by valentine-palazkov** [comment]
> ServiceBusTrigger problem still there. Many time it just keeps waiting.

@rakeshagarwal0292 , do you use Http Client? For some reason ServiceBusTrigger is sensitive about an amount of http connections.

In my scenario I had a message with a bunch of emails to send. Then I was posting emails to our endpoints using HTTP Client in parallel thus making thousands of http connections opened simultaneously because I used an instance of HttpClient for each message.

It was working for a while (up to 50 000 service bus messages processed) but then web job stopped to do any job at all without any visible reason (no errors in logs, nothing).

So the solution was to use a SINGLE HttpClient instance for all messages (injected via DI framework)

Hope it will help

**Comment by rakeshagarwal0292** [comment]
Hi @valentine-palazkov No, I am not directly using HttpClient. There are other libraries like Sendgrid which might be internally using HttpClient or anything like that. How can we verify that if there is any such issue?

**Comment by valentine-palazkov** [comment]
Azure Metrics section would help.

Take also a look at this page for extra details:

https://docs.microsoft.com/en-us/azure/app-service/web-sites-monitor
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-platform-metrics

There is also a valuable note from MS article that could give you an insight:

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#reusing-factories-and-clients

**Comment by rakeshagarwal0292** [comment]
Thanks @valentine-palazkov These docs are very informative. One thing which I could conclude and relate from these is not to instantiate QueueClient again and again, which was missing initially. I have fixed that but the issue is still there.

Let me give you an overview of what is happening on my side. 

1. There are multiple process running on the same machine.
2. One of them is keep putting messages in 9 different queues.
3. Then there are 9 other process which keeps reading from the queue and do their job.

Could this be a problem because the sender and receiver both are on the same machine?
Because both the process trying to set a broker connection from same machine?

**Comment by rakeshagarwal0292** [comment]
So this is happening sometimes when queue is idle for a period. Is this a known issue? 
Any solution?

**Comment by b10-ydinkov** [comment]
We are experiencing this issue with the latest SDK as of july 2021. If not a solution, is there a known work-around?
