### ISSUE TITLE
Beta5 - Method not found: 'FluentBinder<!0> Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1.BindToInput(Microsoft.Azure.WebJobs.IAsyncConverter`2<!0,!!0>)'.

### ISSUE THREAD

**Issue by isaiahwilliams** [Azure/azure-webjobs-sdk#1648]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Develop a custom extension using the Microsoft.Azure..WebJobs version 3.0.0-beta5

2. Initialize the extension using a class that inherits from IExtensionConfigProvider

3. Call  context.AddBindingRule<MyAttribute>().BindToInput(new MyConverter()); in the initialize function

#### Expected behavior

The extension should execute the function to bind the input attribute. 

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

I have not discovered any work arounds yet. 

#### Related information 

Provide any related information 

* Package version 3.0.0-beta5

**Comment by codepossible** [comment]
I have the exact same error. Downgrading to 3.0.0-beta4 resolves the issue for local development. But I cannot deploy the application on to Azure Functions. Same for AddValidator method which gives a warning that it is being deprecated on beta4.

**Comment by MV10** [comment]
Same here converting some Functions V1 projects to V2.
Throws with Functions SDK 1.0.11 or 1.0.12 and webjobs 3.0.0-beta5. 
Must downgrade SDK to 1.0.10 to use webjobs beta4.

**Comment by katebialiatka** [comment]
I can observe the same behavior.
Function was working properly but starting from friday (2018-03-30) we see such kind of error on portal.
Currently, function runs successfully via Visual studio with Microsoft.Azure.WebJobs (3.0.0-beta4) but not on portal.
We use IExtensionConfigProvider for DI. Steps to reproduce are the same as @isaiahwilliams mentioned.

**Error message** is "Method not found: 'Void Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1.BindToInput(System.Func`2<!0,!!0>)'.
System.MissingMethodException:"

**Comment by codepossible** [comment]
Follow the link for announcement below to view the latest version of runtime and SDK currently available in Azure functions. There is a comment on the announcement to get the previous version of Azure Functions Runtime (not recommended).  

https://github.com/Azure/app-service-announcements/issues/94#comment-376647094

**Comment by codepossible** [comment]
I was able to migrate most of the code that I have for my extension to beta5. But still missing a migration path for BindToInput.

**Comment by davidebbo** [comment]
@codepossible so even with the latest packages, you are still seeing the exact error that started this issue when running on Azure?

**Comment by codepossible** [comment]
I am able to build the code with latest packages - Built with Microsoft.NET.Sdk.Functions (v.1.0.12) and Microsoft.Azure.WebJobs.SDK (v3.0.0-beta5), but get the following error when trying to run the code locally and on Azure.

Here is the local stacktrace:
**System.MissingMethodException: Method not found: 'FluentBinder<!0> Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1.BindToInput(Microsoft.Azure.WebJobs.IConverter`2<!0,!!0>)'.**
   at WebJobs.Extensions.AzureRedis.AzureRedisConfiguration.Initialize(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.InvokeExtensionConfigProviders(ExtensionConfigContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostConfigurationExtensions.cs:line 410
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.CreateStaticServices(JobHostConfiguration config) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostConfigurationExtensions.cs:line 110
   at Microsoft.Azure.WebJobs.JobHost.InitializeServices() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 472
   at Microsoft.Azure.WebJobs.JobHost.get_Services() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 484
   at Microsoft.Azure.WebJobs.Script.Utility.CreateMetadataProvider(JobHost host) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs:line 375
   at Microsoft.Azure.WebJobs.Script.ScriptHost.LoadCustomExtensions() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs:line 723
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs:line 540
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment, IScriptEventManager eventManager, ScriptHostConfiguration scriptConfig, ScriptSettingsManager settingsManager, ILoggerFactoryBuilder loggerFactoryBuilder, ProxyClientExecutor proxyClient) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs:line 996

**Comment by CarlosSardo** [comment]
Facing the exact same issue here with my dev machine, using VS2017 15.6.2 and Azure Functions and Web Jobs Tools 15.0.40322.0.
When deployed to Azure it works fine!

**Comment by davidebbo** [comment]
It took a little longer than we would have wanted, but the updated Azure Functions and WebJobs Tools VS extension is now up. Please go ahead and upgrade. The new version is 15.0.40405.0.

Thanks for your patience on this.

**Comment by harjotsmart** [comment]
Thanks @davidebbo , I was facing the same issue and you saved lot of time for me.
