### ISSUE TITLE
ServiceBusAccountAttribute - Account parameter %% value not passed to registered INameResolver

### ISSUE THREAD

**Issue by omega1970** [Azure/azure-webjobs-sdk#1735]
According to the documention of the account parameter

/// - Can be a string containing %% values (e.g. %StagingServiceBus%). The value provided will be passed
///   to any INameResolver registered on the JobHostConfiguration to resolve the actual setting name to use.

#### Repro steps

Step A: In my function code i am using the attribute:
```
        [FunctionName("SAPMetadataUpsertedHandler")]
        [ServiceBusAccount("%SAP-Adapter-Functions%")]
        public static Task HandleMetadata([ServiceBusTrigger(MetadataTopic, MetadataSubscription)]string message, TraceWriter log)
        {
        }
```
Step B: I've registerd the following NameResolver with the JobHostConfiguration:

```
    public class SAPConnectionKeyVaultResolver : INameResolver
    {
        public string Resolve(string name)
        {
            return KeyVaultConfiguration.GetVaultSecretAsync(name).GetAwaiter().GetResult();
        }
    }
```

Step C: Jobhost Configuration:

```
           var config = new JobHostConfiguration
            {
                StorageConnectionString = KeyVaultConfiguration.GetVaultSecretAsync("AzureWebJobsStorage").GetAwaiter().GetResult(),
                NameResolver = new SAPConnectionKeyVaultResolver()
            };

```

#### Expected behavior
The connection string for the servicebus being resolved by the INameResolver

#### Actual behavior

When executing the application (webjob console) i get the following exception:

Error indexing method 'Functions.HandleMetadata'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Functions.HandleMetadata' ---> System.InvalidOperationException : Microsoft Azure WebJobs SDK ServiceBus connection string '%SAP-Adapter-Functions%' is missing or empty.
   at Microsoft.Azure.WebJobs.ServiceBus.MessagingProvider.GetConnectionString(String connectionStringName)
   at Microsoft.Azure.WebJobs.ServiceBus.MessagingProvider.CreateMessagingFactory(String entityPath,String connectionStringName)
   at Microsoft.Azure.WebJobs.ServiceBus.Triggers.ServiceBusTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken)
   End of inner exception
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken)

#### Known workarounds

Did not find any, tried several class, function and parameter position for SerivceBusAccountAttribute.
Tried using the %% notation in the the 'Connection' property of the SeriviceBusTrigger attribute.

#### Related information 

* Package version
Assembly Microsoft.Azure.WebJobs.ServiceBus, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

* Links to source
Not publically available.

**Comment by fabiocav** [comment]
The behavior conflicts with the documentation. Looks like this has been around for a while and impacts 2.x and 3.x
