### ISSUE TITLE
Null ref in FunctionExecutor.NotifyCompleteAsync

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1741]
We're seeing a null ref with the below stack trace in the logs. The scenario is that due to connection thresholds being exceeded by an EventHub triggered function, causing the host to restart while there are in-flight invocations. Those invocations are attempting to complete on a disposed host, leading to this null ref.

Likely we just need a few guards put in place to handle completion callbacks when the host is disposed. We should fix to remove the spurious error logs being written.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.NotifyCompleteAsync(FunctionInstanceLogEntry intanceLogEntry,IDictionary`2 arguments,ExceptionDispatchInfo exceptionInfo)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync[TTriggerValue](TriggeredFunctionData input,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.ServiceBus.EventHubListener.Listener.ProcessEventsAsync(PartitionContext context,IEnumerable`1 messages)
   at Microsoft.ServiceBus.Common.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr,IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
```

Kusto Query (waws-prod-ch1-019):

FunctionsLogs
| where PreciseTimeStamp > datetime(2018-06-07 18:07:47.673) and PreciseTimeStamp < datetime(2018-06-07 18:07:48.295)
| where RoleInstance == "SmallDedicatedWebWorkerRole_IN_355"
| project PreciseTimeStamp, FunctionName, Summary, Details, Level, HostVersion 
| where Level < 3

**Comment by mathewc** [comment]
I logged https://github.com/Azure/azure-webjobs-sdk/issues/1741 recently as well, based on organic log review
