### ISSUE TITLE
Error attempting to add Microsoft.Azure.ServiceBus.Message to ICollector

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-webjobs-sdk#1751]
Creating on behalf of @aeghbal1 from [Azure/azure-functions-vs-build-sdk#104](https://github.com/Azure/azure-functions-vs-build-sdk/issues/104#issuecomment-392941175)

----

We are building our customized Microsoft.Azure.ServiceBus.Message object and when we try to add that message to outputCollector, which we are defining it as ICollector type, we get the following exception (any idea?):

Newtonsoft.Json.JsonSerializationException
HResult=0x80131500
Message=Error getting value from 'ExpiresAtUtc' on 'Microsoft.Azure.ServiceBus.Message'.
Source=Newtonsoft.Json
StackTrace:
at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
at Microsoft.Azure.WebJobs.ServiceBus.Bindings.UserTypeToBrokeredMessageConverter1.Convert(TInput input) at Microsoft.Azure.WebJobs.ServiceBus.Bindings.MessageSenderCollector1.Add(T item)
at McioDoveAndDoleE2eValidator.DoveE2eValidator.Run(String omnibusMessage, ICollector1 outputTopic, IDoveValidationEngineReportingDbContextFactory dbFactory, ISettings settings, ExecutionContext executionContext, TraceWriter log) in D:\dove\src\McioDoveAndDoleE2eValidator\DoveE2eValidator.cs:line 97 at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker2.InvokeAsync(TReflected instance, Object[] arguments)
at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.d__9.MoveNext()

Inner Exception 1:
InvalidOperationException: Operation is not valid due to the current state of the object.

**Comment by jeffhollan** [comment]
@aeghbal1 would be great if you could include a code snippet of the function code and how you are adding to ICollector as well.

**Comment by aeghbal1** [comment]
+ Swapnil

Sent from my Windows 10 phone

________________________________

**Comment by aeghbal1** [comment]
+ Sawpnil

Sent from my Windows 10 phone

________________________________

**Comment by paulbatum** [comment]
There's not enough info to investigate yet. We'd need the code for the function and the derived type. A standalone repro is even better.

**Comment by aeghbal1** [comment]
Swapnil,
Could you please help repoing this?
(basically if you remember we were getting issue when we used Message type in the ICollector)

Thanks,
Arash

**Comment by aeghbal1** [comment]
Thank you Swapnil.

From: Swapnil Nagar
Sent: Wednesday, June 13, 2018 11:17 AM
To: Arash Eghbal <aeghbal@microsoft.com>; Azure/azure-webjobs-sdk <reply@reply.github.com>; Azure/azure-webjobs-sdk <azure-webjobs-sdk@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-webjobs-sdk] Error attempting to add Microsoft.Azure.ServiceBus.Message to ICollector (#1751)

I had a console app which I was experimenting with. Let me send it to you shortly.
From: Arash Eghbal
Sent: Wednesday, June 13, 2018 11:14 AM
To: Azure/azure-webjobs-sdk <reply@reply.github.com>; Azure/azure-webjobs-sdk <azure-webjobs-sdk@noreply.github.com<mailto:azure-webjobs-sdk@noreply.github.com>>; Swapnil Nagar <swnagar@microsoft.com<mailto:swnagar@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [Azure/azure-webjobs-sdk] Error attempting to add Microsoft.Azure.ServiceBus.Message to ICollector (#1751)

Swapnil,
Could you please help repoing this?
(basically if you remember we were getting issue when we used Message type in the ICollector)

Thanks,
Arash

**Comment by aeghbal1** [comment]
I had a console app which I was experimenting with. Let me send it to you shortly.
From: Arash Eghbal
Sent: Wednesday, June 13, 2018 11:14 AM
To: Azure/azure-webjobs-sdk <reply@reply.github.com>; Azure/azure-webjobs-sdk <azure-webjobs-sdk@noreply.github.com>; Swapnil Nagar <swnagar@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-webjobs-sdk] Error attempting to add Microsoft.Azure.ServiceBus.Message to ICollector (#1751)

Swapnil,
Could you please help repoing this?
(basically if you remember we were getting issue when we used Message type in the ICollector)

Thanks,
Arash

**Comment by swapnilnagar** [comment]
[FunctionApp3.zip](https://github.com/Azure/azure-webjobs-sdk/files/2099698/FunctionApp3.zip)

Please find the Test App Attached.
Some prerequisite for running this App
1.	Please provide a valid ServiceBus Connection string at local.settings.json
2.	Please update the Topic name at line 15 in file Function1.cs

Note: We are experiencing this problem with .Net Framework only.

**Comment by jeffhollan** [comment]
[This is the class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage?view=azure-dotnet) you would use instead of `Message` if not wanting to use a native type like `strings`
