### ISSUE TITLE
EventHubs Trigger with "cardinality": "many" fails when input is not valid json

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-webjobs-sdk#1830]
When "cardinality": "many" is set on an Event Hubs trigger (as it should be for best perf), the error below is thrown unless the original input is _valid json_. This conflicts with v1 behavior and breaks [the template example](https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/EventHubTrigger-JavaScript/sample.dat)

The trigger attribute should have a "DefaultType" that is string and not object.

```
System.Private.CoreLib: Exception while executing function: Functions.eventhub. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myEventHubMessages'. Microsoft.Azure.WebJobs.Host: Binding parameters to complex objects (such as 'Object') uses Json.NET serialization.
1. Bind the parameter type as 'string' instead of 'Object' to get the raw values and avoid JSON deserialization, or
2. Change the queue payload to be valid json. The JSON parser failed: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
```

The fix is to default the "many" input to be a string array.

Here's a more complete stacktrace:
```
      => System.Collections.Generic.Dictionary`2[System.String,System.Object]
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.eventhub ---> System.InvalidOperationException: Exception binding parameter 'myEventHubMessages' ---> System.InvalidOperationException: Binding parameters to complex objects (such as 'Object') uses Json.NET serialization.
1. Bind the parameter type as 'string' instead of 'Object' to get the raw values and avoid JSON deserialization, or
2. Change the queue payload to be valid json. The JSON parser failed: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.

   at Microsoft.Azure.WebJobs.Host.Triggers.PocoTriggerArgumentBinding`2.ConvertAsync(TMessage value, Dictionary`2 bindingData, ValueBindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\PocoTriggerArgumentBinding.cs:line 57
   at Microsoft.Azure.WebJobs.Host.ArrayTriggerArgumentBinding`2.BindAsync(TTriggerValue value, ValueBindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\ArraryTriggerArgumentBinding.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync(ValueBindingContext context, Object value, IDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 57
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DelayedException.cs:line 27
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 460
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 426
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 231
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 275
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 75
fail: Function.eventhub[0]
```

https://github.com/Azure/azure-functions-host/pull/3170 has additional context
Issue was brought to attention here: https://github.com/Azure/azure-functions-host/issues/2815

**Comment by mhoeger** [comment]
The fix involves creating a DefaultType for the EventHubs trigger attribute and making sure that it is registered in the metadata provider

cc: @pragnagopa
