### ISSUE TITLE
ApplicationInsightLogger throws an exception when property is added twice

### ISSUE THREAD

**Issue by Kimmen** [Azure/azure-webjobs-sdk#1875]
#### Scenario
I have an Azure Function (V2) that is triggered by collection changes in CosmosDB and should send those changes to a Azure SignalR. But when adding a SignalR message to the collector an exception is thrown from [ApplicationInsightLogger]( azure-webjobs-sdk/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs ):
```
System.ArgumentException
  HResult=0x80070057
  Message=The key already existed in the dictionary.
  Source=System.Collections.Concurrent
  StackTrace:
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyProperty(ISupportProperties telemetry, String key, Object value, String propertyPrefix) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 251
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyProperties(ISupportProperties telemetry, IEnumerable`1 values, String propertyPrefix) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 264
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyScopeProperties(ISupportProperties telemetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 168
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.LogTrace(LogLevel logLevel, IEnumerable`1 values, String formattedMessage) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 201
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 106
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```

*I guess it has nothing to do with the CosmosDB trigger.*
I hope I post this to the correct repo.

#### Repro steps

Added Github repo to illustrate the issue:
https://github.com/Kimmen/issues-AppInsightLoggerSignalRCrash

- Create a new Azure Function V2 project. 
- Make sure it targets netstandard2.0.
- Use following nuget packages:
    - Microsoft.Azure.WebJobs.Extensions.CosmosDB, version 3.0.1-beta2
    - AzureAdvocates.WebJobs.Extensions.SignalRService, version 0.3.0-alpha
- Create function that triggers on CosmosDB collection changes and outputs to Azure SignalR
- Add a message to the SignalR collector.

#### Expected behavior

A signalR message should be sent.

#### Actual behavior

Crashes when adding the message to the collector. 

#### Known workarounds

Remove APPINSIGHTS_INSTRUMENTATIONKEY, removing all logging to ApplicationInsights.

#### Related information 

    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.1-beta2" />
    <PackageReference Include="AzureAdvocates.WebJobs.Extensions.SignalRService" Version="0.3.0-alpha" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.19" />

**Comment by artyombaranovskiytr** [comment]
I'm seeing similar behavior, but in slightly different conditions:
Just trying to request one function from another via typed HttpClient (Microsoft.Extensions.Http 2.1.0).

Here is the exception message and a stack trace from app insights:
```
An error occurred while writing to logger(s). (The key already existed in the dictionary.) The key already existed in the dictionary.
System.AggregateException:
   at Microsoft.Extensions.Logging.Logger.Log (Microsoft.Extensions.Logging, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass6_0`2.<Define>b__0 (Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler+Log.RequestPipelineStart (Microsoft.Extensions.Http, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler+<SendAsync>d__2.MoveNext (Microsoft.Extensions.Http, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__62.MoveNext (System.Net.Http, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
...
Inner exception System.ArgumentException handled at Microsoft.Extensions.Logging.Logger.Log:
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add (System.Collections.Concurrent, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyProperty (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 251)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyProperties (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 264)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyScopeProperties (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 168)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.LogTrace (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 201)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.Log (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 106)
   at Microsoft.Extensions.Logging.Logger.Log (Microsoft.Extensions.Logging, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```


It is likely caused by the fact this HttpClient is using LoggingScopeHttpMessageHandler, which adds the same properties twice to the log (request - once adding to scope, then trying to log it explicitly), while AppinsightsLogger is using .Add on ConcurrentDictionary:
```
protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
...
using (Log.BeginRequestPipelineScope(_logger, request))
{
    Log.RequestPipelineStart(_logger, request);
...
```
[Full source](https://github.com/aspnet/HttpClientFactory/blob/master/src/Microsoft.Extensions.Http/Logging/LoggingScopeHttpMessageHandler.cs)

**Comment by ArtyomBaranovskiy** [comment]
I'm seeing similar behavior, but in slightly different conditions:
Just trying to request one function from another via typed HttpClient (Microsoft.Extensions.Http 2.1.0).

Here is the exception message and a stack trace from app insights:
```
An error occurred while writing to logger(s). (The key already existed in the dictionary.) The key already existed in the dictionary.
System.AggregateException:
   at Microsoft.Extensions.Logging.Logger.Log (Microsoft.Extensions.Logging, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass6_0`2.<Define>b__0 (Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler+Log.RequestPipelineStart (Microsoft.Extensions.Http, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler+<SendAsync>d__2.MoveNext (Microsoft.Extensions.Http, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__62.MoveNext (System.Net.Http, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
...
Inner exception System.ArgumentException handled at Microsoft.Extensions.Logging.Logger.Log:
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add (System.Collections.Concurrent, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyProperty (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 251)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyProperties (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 264)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.ApplyScopeProperties (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 168)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.LogTrace (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 201)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.Log (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 106)
   at Microsoft.Extensions.Logging.Logger.Log (Microsoft.Extensions.Logging, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```


It is likely caused by the fact this HttpClient is using LoggingScopeHttpMessageHandler, which adds the same properties twice to the log (request - once adding to scope, then trying to log it explicitly), while AppinsightsLogger is using .Add on ConcurrentDictionary:
```
protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
...
using (Log.BeginRequestPipelineScope(_logger, request))
{
    Log.RequestPipelineStart(_logger, request);
...
```
[Full source](https://github.com/aspnet/HttpClientFactory/blob/master/src/Microsoft.Extensions.Http/Logging/LoggingScopeHttpMessageHandler.cs)

**Comment by brettsam** [comment]
Good find. I'm fixing this with #1893. Now the last value will be the one that makes it into the Properties dictionary for App Insights.
