### ISSUE TITLE
Webjobs SDK 3.0 AzureWebJobsEnv

### ISSUE THREAD

**Issue by cheng93** [Azure/azure-webjobs-sdk#1908]
Please provide a succinct description of the issue.

The application does not pick up the `AzureWebJobsEnv` settings in Azure.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

Set `AzureWebJobsEnv` to something that isn't `production` in azure

2. Step B

Create a simple webjob, with an `appsettings.[ENVIRONMENT].json`

Include this bit of code in the hostbuilder

```
.ConfigureAppConfiguration((hostContext, config) =>
                {
                    var env = hostContext.HostingEnvironment;

                    config
                        .AddJsonFile(@"config\appsettings.json")
                        .AddJsonFile($"config\\appsettings.{env.EnvironmentName.ToLower()}.json")
                        .AddEnvironmentVariables();
                })
```

#### Expected behavior

The config should load

#### Actual behavior
```
[09/14/2018 10:09:22 > 97b0cb: ERR ] Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'config\appsettings.production.json' was not found and is not optional. The physical path is 'D:\local\Temp\jobs\continuous\EmailWebJob\rsuyvwjo.3ng\config\appsettings.production.json'.
[09/14/2018 10:09:22 > 97b0cb: ERR ]    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
[09/14/2018 10:09:22 > 97b0cb: ERR ]    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
[09/14/2018 10:09:22 > 97b0cb: ERR ]    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
[09/14/2018 10:09:22 > 97b0cb: ERR ]    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
[09/14/2018 10:09:22 > 97b0cb: ERR ]    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
[09/14/2018 10:09:22 > 97b0cb: ERR ]    at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

#### Known workarounds

* On deployment, rename the file to `appsettings.production.json`

#### Related information 

Provide any related information 

* Package version
* Links to source

```
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Host.Storage" Version="3.0.0-beta8" />
```

**Comment by cheng93** [comment]
Took a look into the source code, added 
`.ConfigureHostConfiguration(config => { config.AddEnvironmentVariables(); })` 

at the start of the hostbuilder.

https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.Extensions.Hosting/HostBuilder.cs#L111
https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.Extensions.Hosting/HostBuilder.cs#L134

Looks like `AzureWebJobsEnv` is pretty obsolete.
