### ISSUE TITLE
TimerTrigger for every 15 minutes throws exceptions 

### ISSUE THREAD

**Issue by utkarsh24** [Azure/azure-webjobs-sdk#1980]
I have created the timer trigger webjob using webjob extenstions which is scheduled to run on every 15 mins,

I have published the webjob using visual studio publish method,

but i get following error, can you please help..

Function 'SampleHost.Functions.ProcessEvents' updated status: Last='2018-10-24T10:00:00.0391190+00:00', Next='2018-10-24T10:15:00.0000000+00:00', LastUpdated='2018-10-24T10:00:00.0391190+00:00'
[10/24/2018 10:04:01 > d35386: ERR ] Command 'cmd /c ""run.cmd""' was aborted due to no output nor CPU activity for 121 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.
cmd /c ""run.cmd""
[10/24/2018 10:04:01 > d35386: SYS INFO] Status changed to Failed
[10/24/2018 10:04:01 > d35386: SYS ERR ] System.AggregateException: One or more errors occurred. ---> Kudu.Core.Infrastructure.CommandLineException: Command 'cmd /c ""run.cmd""' was aborted due to no output nor CPU activity for 121 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.
cmd /c ""run.cmd""
   at Kudu.Core.Infrastructure.IdleManager.WaitForExit(IProcess process) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\IdleManager.cs:line 45
   at Kudu.Core.Infrastructure.ProcessExtensions.<Start>d__12.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\ProcessExtensions.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Infrastructure.Executable.<ExecuteAsync>d__31.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\Executable.cs:line 255
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\Executable.cs:line 216
   at Kudu.Core.Infrastructure.Executable.ExecuteReturnExitCode(ITracer tracer, Action`1 onWriteOutput, Action`1 onWriteError, String arguments, Object[] args) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\Executable.cs:line 165
   at Kudu.Core.Jobs.BaseJobRunner.RunJobInstance(JobBase job, IJobLogger logger, String runId, String trigger, ITracer tracer, Int32 port) in C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\BaseJobRunner.cs:line 272
---> (Inner Exception #0) ExitCode: -1, Output: Command 'cmd /c ""run.cmd""' was aborted due to no output nor CPU activity for 121 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed., Error: Command 'cmd /c ""run.cmd""' was aborted due to no output nor CPU activity for 121 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed., Kudu.Core.Infrastructure.CommandLineException: Command 'cmd /c ""run.cmd""' was aborted due to no output nor CPU activity for 121 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.
cmd /c ""run.cmd""
   at Kudu.Core.Infrastructure.IdleManager.WaitForExit(IProcess process) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\IdleManager.cs:line 45
   at Kudu.Core.Infrastructure.ProcessExtensions.<Start>d__12.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\ProcessExtensions.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Infrastructure.Executable.<ExecuteAsync>d__31.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\Executable.cs:line 255<---

**Comment by TheBeardedLlama** [comment]
bump

I was about to submit the same issue

It seems that a timer trigger is ignored when the timeout is calculated, thus failing job even though it is intentionally not supposed to run for x minutes where x is greater than the arbitrary built-in timeout.

**Comment by utkarsh24** [comment]
but still i see no action plan for this issue.

**Comment by TheBeardedLlama** [comment]
@utkarsh24 I think I figured it out, but I don't know if it'll work for you too

I updated the `WebJob Type` to `Continuous` and now it's not throwing for me

silly thing to miss, but still

**Comment by utkarsh24** [comment]
@TheBeardedLlama I fixed  this with adding SCM_COMMAND_IDLE_TIMEOUT and WEBJOBS_IDLE_TIMEOUT appsettings values to 10800(30 min).

**Comment by TheBeardedLlama** [comment]
yeah I was looking at the webjobs timeout too, however I think that's a workaround as opposed to how it's meant to run

hopefully someone from the team here will confirm

**Comment by TheBeardedLlama** [comment]
couldn't find anything in the docs about it, so upon confirmation I will submit a PR to update the docs

**Comment by bartdekeersmaeker** [comment]
Any news on how to solve this issue ?

**Comment by TheBeardedLlama** [comment]
see my post above @bartdekeersmaeker about running in continuous mode

still no official confirmation obviously

**Comment by bartdekeersmaeker** [comment]
@TheBeardedLlama : But it's not a continuous job ? :) No idea if switching this type has any other side-effect ?

**Comment by utkarsh24** [comment]
Any updates ??

**Comment by TheBeardedLlama** [comment]
@bartdekeersmaeker I believe that essentially they are a continuous job; at the very least, it worked for me and I had no errors after I made the change

that's the question I've put to the MS guys/gals with regards to the docs (I think I've submitted an issue somewhere that is...)

**Comment by TheBeardedLlama** [comment]
PS. otherwise you'd have to increase the timeout to a ridiculous amount (e.g. I had some jobs that only had to run once a day...)

**Comment by acds** [comment]
Any update on this....

It seem Illogical to have to set a scheduled WebJob to Continuous?

**Comment by TheBeardedLlama** [comment]
not that illogical if you think about it

there is no obvious way to trigger a scheduled job unless it's already running

worked fine for me with no side effects and none of the reported errors

**Comment by pawod** [comment]
For triggered jobs try to replace 

`host.Run();` by `host.Start();` 

in your Program.cs, it worked for me.

**Comment by Fin3** [comment]
> For triggered jobs try to replace
> 
> `host.Run();` by `host.Start();`
> 
> in your Program.cs, it worked for me.

It worked for me also, and imho it's the right way to do it. 

However to let it work i need to have informations about task scheduling in both the task activation:

``` C#
public async Task RetrieveDataExecution([TimerTrigger("0 */15 * * * *", RunOnStartup = true)] TimerInfo timerInfo, CancellationToken cancellationToken)
```

than in the file Settings.job (that was auto-created during publish process):
``` C#
{

  //    Examples:

  //    Runs every minute
  //    "schedule": "0 * * * * *"

  //    Runs every 15 minutes
  "schedule": "0 */15 * * * *"

  //    Runs every hour (i.e. whenever the count of minutes is 0)
  //    "schedule": "0 0 * * * *"

  //    Runs every hour from 9 AM to 5 PM
  //    "schedule": "0 0 9-17 * * *"

  //    Runs at 9:30 AM every day
  //    "schedule": "0 30 9 * * *"

  //    Runs at 9:30 AM every week day
  //    "schedule": "0 30 9 * * 1-5"
}
```
If I delete the file Settings.job the job will be executed only the first time.
If I delete the parameters from the RetrieveDataExecution function then it will never be executed by the job.

Maybe an azure-webjobs-sdk team member will explain which one is the right way to develop a timertriggered webjob.

**Comment by luizs81** [comment]
I'm having the same problem, in July of 2021.
It seems there is still no clear direction on how to proceed about this so far.

**Comment by luizs81** [comment]
> For triggered jobs try to replace
> 
> `host.Run();` by `host.Start();`
> 
> in your Program.cs, it worked for me.

This is definitely the correct approach. I didn't need to change my WebJob to `Continuous` and it did not throw the time out exception. 
Thanks for posting this.

**Comment by ryanrichard19** [comment]
Thanks found this really helpful. Had this error for the passed 2 days. 
host.Start();  solved my problem
