### ISSUE TITLE
Azure Web Jobs SDK 3.0 Service Bus Extensions Connection String override not respected

### ISSUE THREAD

**Issue by bunceg** [Azure/azure-webjobs-sdk#2027]
Please provide a succinct description of the issue.

#### Repro steps

Create a new 3.0 SDK based web job using Service Bus. Add a Trigger attribute that contains connection string, e.g.

```
public async Task ExecuteAsync(
	[ServiceBusTrigger("synchronizeaccount", Connection = "microsoft.servicebus.connectionstring.synchronizeaccount")]Message msg)
```
#### Expected behavior

The Connection String to be pulled from the app.settings connection string in the same manner as the 2.0 SDK, e.g. a setting of:

_"AzureWebJobsmicrosoft.servicebus.connectionstring.synchronizeaccount": "Endpoint=xxxxxx"_

or, perhaps a preferred new behaviour of something like:

_"microsoft.servicebus.connectionstring.synchronizeaccount": "Endpoint=xxxxxx"_

#### Actual behavior

System crash with error Microsoft Azure WebJobs SDK ServiceBus connection string 'microsoft.servicebus.connectionstring.synchronizeaccount' is missing or empty.

#### Known workarounds

None

#### Related information 

Provide any related information 

See this https://stackoverflow.com/questions/39489025/different-service-bus-connection-strings-for-servicebustrigger-webjob/39502311

Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.1

Stack trace;

```
   at Microsoft.Azure.WebJobs.ServiceBus.ServiceBusAccount.get_ConnectionString() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.ServiceBus\ServiceBusAccount.cs:line 48
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener..ctor(String entityPath, ServiceBusTriggerExecutor triggerExecutor, ServiceBusOptions config, ServiceBusAccount serviceBusAccount, MessagingProvider messagingProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.ServiceBus\Listeners\ServiceBusListener.cs:line 35
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusQueueListenerFactory.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.ServiceBus\Listeners\ServiceBusQueueListenerFactory.cs:line 31
   at Microsoft.Azure.WebJobs.ServiceBus.Triggers.ServiceBusTriggerBinding.CreateListenerAsync(ListenerFactoryContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.ServiceBus\Triggers\ServiceBusTriggerBinding.cs:line 107
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.ListenerFactory.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 449
   at Microsoft.Azure.WebJobs.Host.Listeners.HostListenerFactory.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\HostListenerFactory.cs:line 62
   at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ListenerFactoryListener.cs:line 45
   at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ShutdownListener.cs:line 29
   at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 101
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at MSS.PatronAccount.Processor.Host.WebJob.Program.Main(String[] args) in C:\dev\git\src\Processor.Host.WebJob\Program.cs:line 79
```

**Comment by bunceg** [comment]
This seems to work now.... I think it was to do with the connection string not being in the root appsettings.json but it was in a appsettings.local.json file
