### ISSUE TITLE
Templated QueueTrigger name fails to resolve in 3.0.3.

### ISSUE THREAD

**Issue by panesofglass** [Azure/azure-webjobs-sdk#2063]
Defining a `[QueueTrigger("%InputQueue%")]` fails to resolve the `InputQueue` from the `App.config` `appSettings`.

#### Repro steps

Provide the steps required to reproduce the problem

1. Add an `App.config` setting in `appSettings` for `InputQueue`, e.g. `<add key="InputQueue" value="queue" />`

2. Set the `QueueTriggerAttribute` to use the templated value, e.g. `[QueueTrigger("%InputQueue%")]`

#### Expected behavior

Prior to 3.0.*, the queue trigger would pick up the queue name from the `App.config` `appSettings`.

#### Actual behavior

Runtime exception:

```
Unhandled Exception: Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.processQueueMessage' ---> System.InvalidOperationException: '%InputQueue%' does not resolve to a value.
   at Microsoft.Azure.WebJobs.Host.NameResolverExtensions.ResolveWholeStringCore(INameResolver resolver, String resolve, Boolean throwOnFailure) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\NameResolverExtensions.cs:line 99
   at Microsoft.Azure.WebJobs.Host.NameResolverExtensions.ResolveWholeString(INameResolver resolver, String resolve) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\NameResolverExtensions.cs:line 36
   at Microsoft.Azure.WebJobs.Host.Queues.Triggers.QueueTriggerAttributeBindingProvider.Resolve(String queueName) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Triggers\QueueTriggerAttributeBindingProvider.cs:line 99
   at Microsoft.Azure.WebJobs.Host.Queues.Triggers.QueueTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Triggers\QueueTriggerAttributeBindingProvider.cs:line 61
   at Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs:line 22
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 190
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 167
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 83
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 112
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 79
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.GetAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 64
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.Create(CancellationToken shutdownToken, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostContextFactory.cs:line 101
   at Microsoft.Azure.WebJobs.JobHost.InitializeHostAsync(CancellationToken cancellationToken, TaskCompletionSource`1 initializationTask) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 359
   at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 99
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WebJobExample.Program.main(String[] argv) in C:\Code\fsharp-azure-webjob\WebJobExample\Program.fs:line 19
```

#### Known workarounds

None.

#### Related information 

* Package version: Microsoft.Azure.WebJobs.Core 3.0.3
* Links to source: https://github.com/panesofglass/fsharp-azure-webjob/tree/netcoreapp2.1

**Comment by panesofglass** [comment]
Seems this is undocumented. I was able to fix it by adding a singleton:

``` fsharp
let configNameResolver =
    { new INameResolver with
        member __.Resolve(name) =
            ConfigurationManager.AppSettings.[name] }

[<EntryPoint>]
let main argv =
    let builder =
        HostBuilder()...
            .ConfigureServices(fun services ->
                // This seems to correctly add the name resolver for the QueueTrigger
                services.AddSingleton(configNameResolver) |> ignore
            )
            // rest of configuration
    use host = builder.Build()
    host.Run()
    0
```

**Comment by ranouf** [comment]
Hi, I have the same error.

@panesofglass could you give more details about your fix, I dont know how to implement it, it does not seem to be C#.

Thanks :)

**Comment by panesofglass** [comment]
@ranouf, the above is F#. For C#, the following should work:

``` csharp
class ConfigNameResolver : INameResolver
{
    public string Resolve(string name)
    {
        return ConfigurationManager.AppSettings[name];
    }
}

class Program
{
    public static void Main(string[] args)
    {
        var configNameResolver = new ConfigNameResolver();
        var builder =
            new HostBuilder()
                .ConfigureServices(services =>
                    // This seems to correctly add the name resolver for the QueueTrigger
                    services.AddSingleton(configNameResolver);
                );
        using (var host = builder.Build())
        {
            host.Run();
        }
    }
}
```

**Comment by ranouf** [comment]
Thanks, it works!

**Comment by MirzaMerdovic** [comment]
Thanks @panesofglass I can confirm that I have this same issue when trying to run Azure Durable Function in Linux Container and I had to do the same workaround. 
Although my INameResolver implementation is the same as the DeafaultNameResolver in [Azure WebJobs](https://github.com/Azure/azure-webjobs-sdk/blob/aeabc5f43f7c50ca67267cbfa429a08fc68623a9/src/Microsoft.Azure.WebJobs.Host/DefaultNameResolver.cs), but I had to include the "Values" prefix in order to retrieve the value `_configuration[$"Values:{name}"]`, of course this implies that the values are under `AppSettings.Values` inside `appsettings.json`.

**Comment by pragnagopa** [comment]
@fabiocav / @brettsam  - FYI

**Comment by mdurini** [comment]
We faced the same issue. We tried to publish the azure function app from Visual Studio 2019 version 16.9.4 and we discovered that the application setting that we configured in the "Manage Azure app service settings" were ignored if the setting was "classname:propertyname" (example "Idp:Cloud")
This problem is not happening with settings without the class name (example "IsScopeMonitored")
We didn't tried to configure the settings directly from the azure portal.

**Comment by textbytext** [comment]
Hello.
The problem is in the FunctionIndexProvider.cs file.
```
FunctionIndexer indexer = new FunctionIndexer(_triggerBindingProvider, 
...
_instanceServicesFactory, 
null, 
_sharedQueue, 
...
_defaultRetryStrategy); 
```
The **INameResolver** does not passing (**null** instead) to the constructor.
