### ISSUE TITLE
Azure web job stop sending data and restart sending data unexpectedly on event hub

### ISSUE THREAD

**Issue by Mandeep9542** [Azure/azure-webjobs-sdk#2119]
Hi, 

I have a continuous web job that reads random data from a CSV file and send them to Azure Event hub. 
When the job is started, it starts to send data to event hub instantly and is supposed to continue until it is manually stopped. 

The issue is that at a certain point of time, the web job stops sending data to event but would eventually restart sending data automatically after some time.

Here is a snapshot of the Event Hub metric for the past 7 days: 
![image](https://user-images.githubusercontent.com/32157552/52692528-8f1d7280-2f7d-11e9-99c2-c20e4d5f6647.png)

I enabled logging and here is the exception thrown:
<EventData>
            <Data>Application: DataGenerator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean)
   at DataGenerator.Program.SendData()
   at DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, DataGenerator.Program, System.Object[])
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeAsync(System.__Canon, System.Object[])
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1+&lt;InvokeAsync&gt;d__0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+&lt;ExecuteWithWatchersAsync&gt;d__31.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+&lt;ExecuteWithLoggingAsync&gt;d__2c.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+&lt;ExecuteWithLoggingAsync&gt;d__13.MoveNext()

Exception Info: Microsoft.Azure.WebJobs.Host.FunctionInvocationException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+&lt;ExecuteWithLoggingAsync&gt;d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+&lt;TryExecuteAsync&gt;d__1.MoveNext()
   at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw()
   at Microsoft.Azure.WebJobs.JobHost+&lt;CallAsyncCore&gt;d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.JobHost.Call(System.Reflection.MethodInfo)
   at DataGenerator.Program.Main()

</Data>

Can anyone please help?
Thanks

**Comment by fabiocav** [comment]
Are you spinning up a background thread to run the code that is attempting to create a file?

**Comment by StingyJack** [comment]
@fabiocav related? https://github.com/Azure/azure-webjobs-sdk/issues/2087#issuecomment-472638095
