### ISSUE TITLE
Runtime error - Failed to validate Microsoft Azure WebJobs SDK Dashboard connection string

### ISSUE THREAD

**Issue by markmcgookin** [Azure/azure-webjobs-sdk#2160]
Please provide a succinct description of the issue.

#### Repro steps

Simple really. Create a sample webjob with the most basic Main() shown in the example repo

`static void Main(string[] args)
        {
            var builder = new HostBuilder();
            builder.ConfigureWebJobs(b =>
                    {
                        b.AddAzureStorageCoreServices();
                    });
            var host = builder.Build();
            using (host)
            {
                host.Run();
            }
        }`

No matter where I put the connection strings in appsettings.json or appsettings.development.json 

```
{
    "Storage": "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;",
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;",
    "AzureWebJobsDashboard": "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;",
    "ConnectionStrings": {
        "Storage": "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;",
        "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;",
        "AzureWebJobsDashboard": "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;"
    }
}
```

Or even if I add them manually in "ConfigureAppConfiguration"

```
config.AddInMemoryCollection(new Dictionary<string, string>
                        {
                            { "AzureWebJobsStorge", "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;" },
                            { "AzureWebJobsDashboard", "DefaultEndpointsProtocol=https;AccountName=VALIDACCOUNTNAME;AccountKey=VALIDACCOUNTKEY;" }
                        });

```

I get the exact same error every time. 

`Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll: 'Failed to validate Microsoft Azure WebJobs SDK Dashboard connection string. The Microsoft Azure Storage account connection string is not formatted correctly. Please visit https://go.microsoft.com/fwlink/?linkid=841340 for details about configuring Microsoft Azure Storage connection strings.'
   at Microsoft.Azure.WebJobs.Host.Executors.StorageAccountParser.ParseAccount(String connectionString, String connectionStringName, IServiceProvider services) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\StorageAccountParser.cs:line 38
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.ParseAccount(String connectionStringName, String connectionString) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultStorageAccountProvider.cs:line 222
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.ParseAccount(String connectionStringName) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultStorageAccountProvider.cs:line 217
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.get_DashboardAccount() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultStorageAccountProvider.cs:line 134
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.<CreateAndValidateAccountAsync>d__26.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultStorageAccountProvider.cs:line 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.<TryGetAccountAsync>d__27.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultStorageAccountProvider.cs:line 208
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.<CreateJobHostContextAsync>d__1.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostConfigurationExtensions.cs:line 257
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.JobHost.<InitializeHostAsync>d__44.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 427
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__25.MoveNext() in C:\projects\azure-webjobs-sdk-`

Looking at the source, all the code that these reference in the stack seems to have been "Broken Out" of the repo so I have no idea where to look or what the problem could be.

using these packages

`<ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.6" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Logging" Version="3.0.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.2.0" />
  </ItemGroup>`

#### Expected behavior

The webjob to run and fire on a timer.

#### Actual behavior

Application crashes at runtime.

#### Known workarounds

None

**Comment by jdrake3** [comment]
@markmcgookin how did you resolve this?

**Comment by markmcgookin** [comment]
I believe that it was just ignorance about setting up a webjob using the v3 style of configuration. Config probably looks something like this:

```
static void Main(string[] args)
{
    var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
    environment = string.IsNullOrEmpty(environment) ? "development" : environment;
    Console.WriteLine($"Current Environment : {(string.IsNullOrEmpty(environment) ? "Development" : environment)}");

    var assemblyPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

    var configBuilder = new ConfigurationBuilder()
        .SetBasePath(assemblyPath)
        .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: true)
        .AddEnvironmentVariables();

    var config = configBuilder.Build();

    var builder = new HostBuilder();
            builder.ConfigureWebJobs(b =>
            {
                b.AddAzureStorageCoreServices();
                b.AddTimers();
                b.AddServiceBus(c =>
                    {
                        c.ConnectionString = config["ServiceBusConnectionString"];
                    });
            }).ConfigureServices((context, services) =>
            {
                services.AddTransient<IStorageClient, AzureStorageClient>();
            }
    var host = builder.Build();
    using (host)
    {
        host.Run();
    }
}
```

And config

```
<ItemGroup>
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="3.4.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.6" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="3.0.3" />
</ItemGroup>
```

Then my webjobs use a service bus trigger so I have all the stuff in to support that, but the host builder should pick it up based on the fact that it has the trigger attribute in it's arguments

```
public async Task HandleOne([ServiceBusTrigger("servicebusqueue")] Message incommingmessage)
        {
```
