### ISSUE TITLE
I/O race condition detected while copying memory in CompositeTraceWriter

### ISSUE THREAD

**Issue by divyagandhisethi** [Azure/azure-webjobs-sdk#2354]
```
System.IndexOutOfRangeException : Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src,Int32 srcOffsetBytes,Array dst,Int32 dstOffsetBytes,Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer,Int32 index,Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.InvokeTextWriter(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.ConsoleTraceWriter.InvokeTextWriter(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.Trace(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.LogFunctionStartedAsync(FunctionStartedMessage message,CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.LogFunctionStartedAsync(FunctionStartedMessage message,IFunctionOutputDefinition functionOutput,ParameterHelper parameterHelper,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)
```

Seeing more issues of this currently in CRIs.  Looks similar to #1533

**Comment by divyagandhii** [comment]
Also https://github.com/Azure/azure-functions-durable-extension/issues/691

**Comment by mathewc** [comment]
Related to https://github.com/Azure/azure-webjobs-sdk/issues/1861?
