### ISSUE TITLE
A bug in Microsoft.Azure.WebJobs.Extensions.CosmosDB version 3.0.5

### ISSUE THREAD

**Issue by irriss** [Azure/azure-webjobs-sdk#2390]
"continuation can not be null or empty" - error in valid cosmos db call when using 3.0.5
same code works fine if change version to 3.0.3

#### Repro steps

I have Azure durable function like this

```
        [FunctionName("GetProfiles")]
        public async Task<ScrollableList<Profile>> GetProfiles([ActivityTrigger] ProfilesQueryParameters queryParameters, ILogger log)
        {
            log.LogDebug($"Load another bunch of profiles: {queryParameters.Serialize()}");
            return await _profilesService.GetAsync(queryParameters, null); //this goes into Cosmos Db and loads batch of items
        }
```
#### Expected behavior

return the call with batch of items

#### Actual behavior

NullReference exception:

```
[19/12/2019 2:43:00 AM] Executed 'GetProfiles' (Failed, Id=15a84ca4-861d-4dd9-88d5-cceff57d691e)
[19/12/2019 2:43:00 AM] System.Private.CoreLib: Exception while executing function: GetProfiles. Microsoft.Azure.DocumentDB.Core: Value cannot be null.
[19/12/2019 2:43:00 AM] Parameter name: continuation can not be null or empty.
[19/12/2019 2:43:00 AM] NCT03314974: Function 'GetProfiles (Activity)' failed with an error. Reason: System.ArgumentNullException: Value cannot be null.
[19/12/2019 2:43:00 AM] Parameter name: continuation can not be null or empty.
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Query.OrderByDocumentQueryExecutionContext.ValidateAndExtractContinuationToken(String requestContinuation, SortOrder[] sortOrders, String[] orderByExpressions)
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Query.OrderByDocumentQueryExecutionContext.InitializeAsync(String requestContinuation, String collectionRid, List`1 partitionKeyRanges, Int32 initialPageSize, SortOrder[] sortOrders, String[] orderByExpressions, CancellationToken cancellationToken)
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Query.OrderByDocumentQueryExecutionContext.CreateAsync(InitParams constructorParams, CrossPartitionInitParams initParams, CancellationToken token)
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass5_0.<<CreateAsync>b__0>d.MoveNext()
[19/12/2019 2:43:00 AM] --- End of stack trace from previous location where exception was thrown ---
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.CreateAsync(InitParams constructorParams, String collectionRid, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, List`1 partitionKeyRanges, Int32 initialPageSize, String requestContinuation, CancellationToken cancellationToken)
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextFactory.CreateSpecializedDocumentQueryExecutionContext(InitParams constructorParams, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, List`1 targetRanges, String collectionRid, Boolean isContinuationExpected, CancellationToken cancellationToken)
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Query.ProxyDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.Documents.Linq.DocumentQuery`1.ExecuteNextPrivateAsync[TResponse](CancellationToken cancellationToken)
[19/12/2019 2:43:00 AM]    at Cosmonaut.Diagnostics.CosmosEventCall.InvokeAsync[TEntity](Func`1 eventCall)
[19/12/2019 2:43:00 AM]    at Cosmonaut.Extensions.CosmosResultExtensions.GetTokenPagedResultsFromQueryToList[T](IQueryable`1 queryable, Int32 pageSize, CancellationToken cancellationToken)
[19/12/2019 2:43:00 AM]    at Cosmonaut.Extensions.CosmosResultExtensions.GetPaginatedResultsFromQueryable[T](IQueryable`1 queryable, CancellationToken cancellationToken, FeedOptions feedOptions)
[19/12/2019 2:43:00 AM]    at Cosmonaut.Extensions.CosmosResultExtensions.GetPagedListFromQueryable[T](IQueryable`1 queryable, CancellationToken cancellationToken)
[19/12/2019 2:43:00 AM]    at Cosmonaut.Extensions.CosmosResultExtensions.ToPagedListAsync[TEntity](IQueryable`1 queryable, CancellationToken cancellationToken)
....
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments)
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 468
[19/12/2019 2:43:00 AM]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278. IsReplay: False. State: Failed. HubName: UpdateMatchingTrialsHubV1. AppName: . SlotName: . ExtensionVersion: 2.0.0. SequenceNumber: 36.

```
#### Known workarounds

Downgrade to 3.0.3

#### Related information 

Provide any related information 

* 3.0.5

**Comment by v-anvari** [comment]
Hi @irriss , Apologies for the delay in response. Let us know if you were able to resolve the issue. If you are still facing the issue, let us know the repro steps, so that we can clone the scenario. Were you using Visual studio to deploy the case?
