### ISSUE TITLE
Azure Functions host fails for Blob Trigger watching a ADLSv2 account

### ISSUE THREAD

**Issue by GuillaumePugnet** [Azure/azure-webjobs-sdk#2408]
## Repro steps
    Create an ADLSv2 account
    Create a Function App (C#, netcoreapp3.1, Azure Functions v3 , blob trigger)
    Configure the binding to use the ALDSv2 account

## Expected behavior
    The blobs creation or update should trigger the function.

## Actual behavior
    The host fails with the following stacktrace :
System.Collections.Generic.KeyNotFoundException: The given key 'LogType' was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobLogListener.GetLogsWithPrefixAsync(List`1 selectedLogs, CloudBlobClient blobClient, String prefix, IWebJobsExceptionHandler exceptionHandler, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Blobs\Listeners\BlobLogListener.cs:line 183

   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobLogListener.ListRecentLogFilesAsync(CloudBlobClient blobClient, DateTime startTimeForSearch, CancellationToken cancellationToken, Int32 hoursWindow, IWebJobsExceptionHandler exceptionHandler) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Blobs\Listeners\BlobLogListener.cs:line 153

   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobLogListener.GetRecentBlobWritesAsync(CancellationToken cancellationToken, Int32 hoursWindow) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Blobs\Listeners\BlobLogListener.cs:line 55

   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.PollLogsStrategy.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Blobs\Listeners\PollLogsStrategy.cs:line 110

   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Blobs\Listeners\ScanBlobScanLogHybridPollingStrategy.cs:line 123

**Comment by josiahvinson** [comment]
Experiencing the same issue. We were tracking the fix mentioned in #2413 but can confirm I'm seeing the exact same behavior with the same scenario as above.

**Comment by josiahvinson** [comment]
@GuillaumePugnet according to #2395, a fix has been pushed to `Microsoft.Azure.WebJobs.Extensions.Storage` v. 3.0.11, out today. Can confirm it works!

**Comment by brettsam** [comment]
Thanks @josiahvinson! I'll close this as it should now be resolved with the new package.
