### ISSUE TITLE
Singleton lock renewal failed for blob 'xxx/host.Listener' with error code 403.

### ISSUE THREAD

**Issue by rahulseth01** [Azure/azure-webjobs-sdk#2435]
Web job is crashing with error "Singleton lock renewal failed for blob 'xxx/host.Listener' with error code 403"

#### Repro steps

Provide the steps required to reproduce the problem
1. Web job is scheduled for every 30 sec and makes 100 parallel calls to API.

2. Intermittently, Web job crashes when on the start of next schedule. (it does not fails while servicebus messages or API calls are failed.
3.  Configuration that is set in Main()
ServicePointManager.DefaultConnectionLimit = Int32.MaxValue;
ServiceBusConfiguration sb = new ServiceBusConfiguration();
            sb.MessageOptions.MaxConcurrentCalls =20;

#### Expected behavior

It should never crash.

#### Actual behavior

It is crashes

#### Known workarounds

Not sure of.

#### Related information 
Storage Version: StorageV2 (general purpose v2) / Standard
Packages:
  <package id="Microsoft.Azure.WebJobs" version="2.3.0" targetFramework="net472" />
  <package id="Microsoft.Azure.WebJobs.Core" version="2.3.0" targetFramework="net472" />
  <package id="Microsoft.Azure.WebJobs.Extensions" version="2.3.0" targetFramework="net472" />
  <package id="Microsoft.Azure.WebJobs.ServiceBus" version="2.3.0" targetFramework="net472" />
  <package id="WindowsAzure.ServiceBus" version="6.0.1" targetFramework="net472" />
  <package id="WindowsAzure.Storage" version="8.7.0" targetFramework="net472" />

Exception:
_2020-02-21T05:52:45  PID[3056] Information Singleton lock renewal failed for blob 'xxx/host.Listener' with error code 403: AuthenticationFailed. The last successful renewal completed at 2020-02-21T05:52:15.58Z (30117 milliseconds ago) with a duration of 22254 milliseconds. The lease period was 60000 milliseconds.
2020-02-21T05:52:46  PID[3056] Error
2020-02-21T05:52:46  PID[3056] Error       Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.<>c__DisplayClass3d.<RenewLeaseImpl>b__3c(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 3688
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299
2020-02-21T05:52:46  PID[3056] Error          --- End of inner exception stack trace ---
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndRenewLease(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 2446
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.<CreateCallbackVoid>b__5(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 120
2020-02-21T05:52:46  PID[3056] Error       --- End of stack trace from previous location where exception was thrown ---
2020-02-21T05:52:46  PID[3056] Error          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2020-02-21T05:52:46  PID[3056] Error          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.Azure.WebJobs.Host.BlobLeaseDistributedLockManager.SingletonLockHandle.<RenewAsync>d__17.MoveNext()
2020-02-21T05:52:46  PID[3056] Error       --- End of stack trace from previous location where exception was thrown ---
2020-02-21T05:52:46  PID[3056] Error          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2020-02-21T05:52:46  PID[3056] Error          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.Azure.WebJobs.Host.SingletonManager.RenewLeaseCommand.<ExecuteAsync>d__4.MoveNext()
2020-02-21T05:52:46  PID[3056] Error       --- End of stack trace from previous location where exception was thrown ---
2020-02-21T05:52:46  PID[3056] Error          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2020-02-21T05:52:46  PID[3056] Error          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__14.MoveNext()
2020-02-21T05:52:46  PID[3056] Error       --- End of stack trace from previous location where exception was thrown ---
2020-02-21T05:52:46  PID[3056] Error          at Microsoft.Azure.WebJobs.Host.Timers.WebJobsExceptionHandler.<>c__DisplayClass3_0.<OnUnhandledExceptionAsync>b__0()
2020-02-21T05:52:46  PID[3056] Error          at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
2020-02-21T05:52:46  PID[3056] Error          at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2020-02-21T05:52:46  PID[3056] Error          at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2020-02-21T05:52:46  PID[3056] Error          at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2020-02-21T05:52:46  PID[3056] Error          at System.Threading.ThreadHelper.ThreadStart()_

**Comment by rahulseth01** [comment]
Package Version:
"Microsoft.Azure.WebJobs" version="2.3.0"
"Microsoft.Azure.WebJobs.Core" version="2.3.0"
"Microsoft.Azure.WebJobs.Extensions" version="2.3.0"
"Microsoft.Azure.WebJobs.ServiceBus" version="2.3.0"
"WindowsAzure.ServiceBus" version="6.0.1"
"WindowsAzure.Storage" version="8.7.0"

**Comment by rahulseth01** [comment]
Here is some update on this issue:
It seems issue was due to different location region for Azure Web API & Storage Account.
After moving the resources in some region, it resolved the issue.
This could be a KB article for all. :-)
