### ISSUE TITLE
Microsoft.Azure.Webjobs.Scripts.ExtensionsMetadataGenerator 1.1.6 can't detect blobtriggerattributes

### ISSUE THREAD

**Issue by d3ullist** [Azure/azure-webjobs-sdk#2455]
#### Repro steps

Create new azure function app, blobtrigger from the visual studio template.
Install nuget package Microsoft.Azure.Webjobs.Scripts.ExtensionsMetadataGenerator 1.1.6 
Build/ run the project

#### Expected behavior

Function builds/ starts.

#### Actual behavior

Build error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.InvalidOperationException: Could not load type 'Microsoft.Azure.WebJobs.BlobTriggerAttribute'.
   at MakeFunctionJson.TypeUtility.ToReflectionType(TypeReference typeDef)
   at MakeFunctionJson.TypeUtility.ToReflection(CustomAttribute customAttribute)
   at MakeFunctionJson.TypeUtility.GetResolvedAttribute(ParameterDefinition parameter, CustomAttribute customAttribute)
   at MakeFunctionJson.ParameterInfoExtensions.<>c__DisplayClass1_0.<ToFunctionJsonBindings>b__1(CustomAttribute a)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.ParameterInfoExtensions.ToFunctionJsonBindings(ParameterDefinition parameterInfo)
   at MakeFunctionJson.MethodInfoExtensions.<>c.<ToFunctionJson>b__6_1(ParameterDefinition p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodDefinition method, String assemblyPath)
   at MakeFunctionJson.FunctionJsonConverter.GenerateFunctions(IEnumerable`1 types)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()
Error generating functions metadata
	FunctionApp1	C:\Users\incri\.nuget\packages\microsoft.net.sdk.functions\3.0.3\build\Microsoft.NET.Sdk.Functions.Build.targets	41	
```

#### Known workarounds

Downgrade to 1.1.5

#### Related information 

Test project for reproduction https://drive.google.com/open?id=1xc5FsPN0ubG2kvzGFnr-bDXF7yNu0FcR

**Comment by bbrandt** [comment]
I get a similar error for `ServiceBusTriggerAttribute` with 1.1.6 of `ExtensionsMetadataGenerator`.  Same workaround.  Downgrading to 1.1.5 gets around it.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.InvalidOperationException: Could not load type 'Microsoft.Azure.WebJobs.ServiceBusTriggerAttribute'.
   at MakeFunctionJson.TypeUtility.ToReflectionType(TypeReference typeDef)
   at MakeFunctionJson.TypeUtility.ToReflection(CustomAttribute customAttribute)
   at MakeFunctionJson.TypeUtility.GetResolvedAttribute(ParameterDefinition parameter, CustomAttribute customAttribute)
   at MakeFunctionJson.ParameterInfoExtensions.<>c__DisplayClass1_0.<ToFunctionJsonBindings>b__1(CustomAttribute a)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.ParameterInfoExtensions.ToFunctionJsonBindings(ParameterDefinition parameterInfo)
   at MakeFunctionJson.MethodInfoExtensions.<>c.<ToFunctionJson>b__6_1(ParameterDefinition p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodDefinition method, String assemblyPath)
   at MakeFunctionJson.FunctionJsonConverter.GenerateFunctions(IEnumerable`1 types)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()
Error generating functions metadata
	CalculationService	C:\src\my-project\src\packages\microsoft.net.sdk.functions\3.0.5\build\Microsoft.NET.Sdk.Functions.Build.targets	41	
Error		Metadata generation failed.	CalculationService	C:\src\my-project\src\packages\microsoft.net.sdk.functions\3.0.5\build\Microsoft.NET.Sdk.Functions.Build.targets	41	
```

**Comment by v-anvari** [comment]
Hi @d3ullist, I am able to build successfully with the latest package references.

 <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />

1>Done building project "FunctionApp4.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Do let us know if you are still facing an issue with the latest package

**Comment by d3ullist** [comment]
Using v1.2.0 the build error no longer seems to occur
