### ISSUE TITLE
Durable function timeout exception bug

### ISSUE THREAD

**Issue by ComeChao** [Azure/azure-webjobs-sdk#2652]
This is moved from Azure Durable Functions. (https://github.com/Azure/azure-functions-durable-extension/issues/1599)

I have an Azure Durable Function whose host.json file sets all functions to never timeout:
{ "version": "2.0", "functionTimeout": "-1" } }

When the durable function is run though the activity function called by the orchestrator function gets a timeout after the default 30 minutes:

Timeout value of 00:30:00 was exceeded by function: LongRunningActivity

Microsoft.Azure.WebJobs.Host.FunctionTimeoutException: at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+d__29.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 624) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)

The documentation states that the timeout defined in host.json should apply to all functions in the function app yet the activity function fails the rule.

Is there a fix or a workaround other than setting the timeout to something like "12:00:00" (12 hours)?

**Comment by ComeChao** [comment]
I tried these changes to host.json:

{
"version": "2.0",
"functionTimeout": -1
}
and
{
"version": "2.0",
"functionTimeout": "-01:00:00"
}

and got the Timeout Exception in both cases.

2020-12-09T20:27:05.997 [Error] Timeout value of 00:30:00 exceeded by function 'LongRunningActivity' (Id: ''). Initiating cancellation.

The stack trace is this:

at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryHandleTimeoutAsync(Task invokeTask, CancellationToken shutdownToken, Boolean throwOnTimeout, CancellationToken timeoutToken, TimeSpan timeoutInterval, IFunctionInstance instance, Action onTimeout) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 624
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 535
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 492
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 438
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 245
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 295
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstanceEx, CancellationToken cancellationToken, ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 97. IsReplay: False. State: Failed. HubName: x. AppName: x. SlotName: Production. ExtensionVersion: 2.2.2. SequenceNumber: 13.

I found the source code here: https://raw.githubusercontent.com/Azure/azure-webjobs-sdk/master/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs

The issue seems to be around ExecuteWithWatchersAsync which calls StartFunctionTimeout. StartFunctionTimeout sets a timer that handles the timeout with OnFunctionTimeout. Somehow a TimeoutAttribute is passed as a parameter and its TimeSpan is set to 30s. It looks like this is an Azure Functions bug but this obviously requires more research.

**Comment by mathewc** [comment]
What SKU are you running in? The limits for timeout values by SKU are here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout.

Can you share your function app name/info, or an invocation ID for a failed function that we can look into? What are the code details of your function - is it a .NET function with a [Timeout] attribute applied directly to it (which will override host level settings)?

**Comment by ComeChao** [comment]
SKU: Premium

Target framework: .NET Core 3.1

packages:
Microsoft.Azure.Functions.Extensions (1.0.0)
Microsoft.Azure.Webjobs (3.0.16)
Microsoft.Azure.Webjobs.Extensions.DurableTask (2.2.2)
Microsoft.NET.Sdk.Functions (3.0.9)

The  activity function does not have a Timeout attribute.

This is one invocation of the activity function:
Date (UTC)		Success	Result Code 	Duration (ms)	Operation Id
2020-12-09 19:57:05.952 Error	0		1800088		030fe4ee55f7b74b9287e8ec85f6149e

This are the invocation details:

2020-12-09 20:27:06.014
Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: '6e41b4e6-dbe2-42b0-b125-eb14b53a4a21'). Initiating cancellation.
Error

2020-12-09 20:27:06.062
Executed '{functionName}' ({status}, Id={invocationId}, Duration={executionDuration}ms)
Error

2020-12-09 20:27:06.062
Executed 'GenerateExtract_Worker' (Failed, Id=6e41b4e6-dbe2-42b0-b125-eb14b53a4a21, Duration=1800086ms)
Error

2020-12-09 20:27:06.077

Error

I hope the above helps.

**Comment by ComeChao** [comment]
Also run the Durable Function with ""functionTimeout": "02:00:00" and also got the timeout excepton. 'GenerateExtract_Worker' is an activity function called by an orchestrator function:

2020-12-11T16:58:51  Welcome, you are now connected to log-streaming service. **The default timeout is 2 hours.** Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2020-12-11T16:59:51  No new trace in the past 1 min(s).
2020-12-11T17:00:51  No new trace in the past 2 min(s).
2020-12-11T17:01:51  No new trace in the past 3 min(s).
2020-12-11T17:02:51  No new trace in the past 4 min(s).
2020-12-11T17:03:51  No new trace in the past 5 min(s).
2020-12-11T17:04:51  No new trace in the past 6 min(s).
2020-12-11T17:05:51  No new trace in the past 7 min(s).
2020-12-11T17:06:51  No new trace in the past 8 min(s).
2020-12-11T17:07:51  No new trace in the past 9 min(s).
2020-12-11T17:08:51  No new trace in the past 10 min(s).
2020-12-11T17:09:51  No new trace in the past 11 min(s).
2020-12-11T17:10:42.993 [Error] **Timeout value of 00:30:00 exceeded** by function 'GenerateExtract_Worker' (Id: 'db914cf6-3078-4bd4-a3af-bdc5b7112843'). Initiating cancellation.
2020-12-11T17:10:43.044 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=db914cf6-3078-4bd4-a3af-bdc5b7112843, Duration=1800136ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker
2020-12-11T17:10:43.126 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: 'b1bd37d7-612b-4496-b970-02ae20cd3722'). Initiating cancellation.
2020-12-11T17:10:43.131 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: '194dc5dc-f89e-46fd-ba95-a286c1e6d748'). Initiating cancellation.
2020-12-11T17:10:43.131 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: '194dc5dc-f89e-46fd-ba95-a286c1e6d748'). Initiating cancellation.
2020-12-11T17:10:43.133 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: '6c7c561a-95c7-45c3-bcdd-d877a5a792cd'). Initiating cancellation.
2020-12-11T17:10:43.326 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=194dc5dc-f89e-46fd-ba95-a286c1e6d748, Duration=1800320ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker
2020-12-11T17:10:43.343 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=6c7c561a-95c7-45c3-bcdd-d877a5a792cd, Duration=1800354ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker
2020-12-11T17:10:43.376 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=b1bd37d7-612b-4496-b970-02ae20cd3722, Duration=1800334ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker


**This means there is no known workaround at this moment.**

**Comment by MSIT-BPSC-IOT** [comment]
Do we have any update on this? I am facing the same problem where the activity function is not honoring host.json.

**Comment by v-anvari** [comment]
Hi @ComeChao , Apologies for the delay, Were you able to solve this? Kindly provide the Function App name and Location for us to check the logs.

**Comment by shshivani** [comment]
@ComeChao Were you able to resolve the issue?

**Comment by ComeChao** [comment]
Yes, thanks.

**Comment by shshivani** [comment]
Can you help me with the settings? I am facing same issue.

**Comment by avillaca** [comment]
I have this on the host,json:
{
  "version": "2.0",
  "functionTimeout": "-1",
...
}
and added a timeout to each of my worker functions:
[Timeout("00:59:00")]
[FunctionName("DoSomething_Worker")]


That's what I did. It works for me as of now. Someday the worker will timeout. When that happens we may refactor and deploy the function somewhere else where there are no timeouts like an AKS cluster. Good luck!

**Comment by shshivani** [comment]
Thank you so much.

**Comment by Hima2021-rajesh** [comment]
Microsoft.Azure.WebJobs.Host.FunctionTimeoutException:
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryHandleTimeoutAsync>d__35.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.32.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:670)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeWithTimeoutAsync>d__33.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.32.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:586)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__32.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.32.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:542)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.32.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:320)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.32.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:367)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__18.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.32.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:108)

Can anyone please help me to understand this issue, when requesting the data, I get timeout.
