### ISSUE TITLE
web job SDK should gracefully handle azure storage unavailability

### ISSUE THREAD

**Issue by Liphi** [Azure/azure-webjobs-sdk#2719]
Hi, I have a timer-triggered azure web job and i'm using the latest .net core web job v3 SDK. Trigger interval is 1 hour TimerTriggerAttribute.UseMonitor is true. Whenever the underlying AzureWebJobsStorage storage account is unavailable (easily repro-able by shutting down the network of the machine where web job runs on), unhandled exception thrown from background thread ( which is spawned by web job sdk) crashes the web job process.
I assume, hopefully, the underlying web job framework have some efficient mechanism to detect process crash and bring up the process back ASAP. But I think process crash like this should ideally be avoided. My expectation is web job SDK should gracefully handle unavailability of dependencies like storage account, and not crash process.

**Comment by v-anvari** [comment]
Hi @Liphi , Thank you for the feedback, We shall repro this issue and validate the errors.

**Comment by v-anvari** [comment]
Hi @Liphi , Apologies for the delayed response, I was unable to repro the above mentioned scenario, My function App could run successfully.
Can you explain us the scenario in detail, can we get the stack trace, and were you able to identify the reason of the unhandled exception. When you say to shutdown the network, does that mean to interrupt the debug ? because, that still works as expected.

**Comment by Liphi** [comment]
by 'shutdown the network', i mean, to disconnect the network on the machine where the timer-triggered web job runs. for example, if you run timer-triggered web job on your dev box, then disconnect the network so that your dev box can't access internet.
after network is down, the web job is not able to connect to any azure storage. web job is crashed when the timer of the web job kicks in, complaining lease renewal fails.

**Comment by v-anvari** [comment]
Hi @Liphi , I will try to repro it for an hour, but for every minute, the timer triggers even if there is no network.

**Comment by Liphi** [comment]
Please set the timer schedule longer than 1 minute (like: 2 minutes), and make sure AzureWebJobsStorage is configured on appSettings.json:

{
  "AzureWebJobsStorage": "connection string to an azure storage account"
}

**Comment by v-anvari** [comment]
Hi @Liphi , I reproduced the issue and this is how I get the output, Can you confirm 
![image](https://user-images.githubusercontent.com/66122429/121686786-3fb0c800-cadf-11eb-85e1-d4d68588d151.png)

**Error message**: Singleton lock renewal failed for blob 'c127cb70b77dd4cd468fe28d4e60acba/_2719.Function.Run.Listener' with error code 0. The last successful renewal completed at 2021-06-11T12:30:05.583Z (76960 milliseconds ago) with a duration of 322 milliseconds. The lease period was 60000 milliseconds.

**Comment by Liphi** [comment]
yes, this is the same unhandled exception which crashes my process. thanks for repro.

**Comment by v-anvari** [comment]
Triaging this issue for required fixes.

**Repro steps:**
1. Create a console application
2. Add a timer trigger function
3. Connect to any Azure storage account 
4. Debug the Function App locally
5. Disconnect the Network from the local system where the web job runs

**Actual result:** 
The Function App runs successfully when there is Network. 
Throws an unhandled exception when the Network is disconnected

**Error**: Singleton lock renewal failed for blob 'c127cb70b77dd4cd468fe28d4e60acba/_2719.Function.Run.Listener' with error code 0. The last successful renewal completed at 2021-06-14T16:50:41.399Z (84868 milliseconds ago) with a duration of 389 milliseconds. The lease period was 60000 milliseconds.

**Unhandled Exception:**
Inner Exception 1:
HttpRequestException: No such host is known.

Inner Exception 2:
SocketException: No such host is known.

**Stack Trace:**
Microsoft.Azure.Storage.StorageException
  HResult=0x80131500
  Message=No such host is known.
  Source=Microsoft.Azure.Storage.Common
  StackTrace:
   at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Host.StorageBaseDistributedLockManager.SingletonLockHandle.<RenewAsync>d__17.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host.Storage\Singleton\BlobLeaseDistributedLockManager.cs:line 349
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.SingletonManager.RenewLeaseCommand.<ExecuteAsync>d__4.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonManager.cs:line 337
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__14.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs:line 147
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Host.Timers.WebJobsExceptionHandler.<>c__DisplayClass3_0.<OnUnhandledExceptionAsync>b__0() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\WebJobsExceptionHandler.cs:line 55
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ThreadHelper.ThreadStart()

**Source:**

`
```
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace _2719
{
    class Program
    {
        static async Task Main()
        {
            var builder = new HostBuilder();
            builder.ConfigureWebJobs(b =>
            {
                b.AddAzureStorageCoreServices();
                b.AddAzureStorage();
                b.AddTimers();
            });
            builder.ConfigureLogging((context, b) =>
            {
                b.AddConsole();
            });
            var host = builder.Build();
            using (host)
            {
                host.Run();
            }
        }
    }
    public class Function
    {
        public static void Run([TimerTrigger("0 */2 * * * *")] TimerInfo timer, ILogger logger)
        {
            logger.LogInformation($"Running job for timer. Next 3 runs are: {timer.FormatNextOccurrences(3)}");
        }
    }
}
```
`
**Appsettings.json:**
{
  "ConnectionStrings": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=..........."
  }
}

Console App - .NetCoreapp3.1
