### ISSUE TITLE
`beta.5` Seems Very Broken with Queues

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-webjobs-sdk#2753]
Please provide a succinct description of the issue.

#### Repro steps

Upgrading from `beta.1` to `beta.5`, Queues stop working and appear to silently fail.  Messages immediately get sent to point queue without any exception/warning/message provided.

Sample output:

```
Host.Startup: Information: Found the following functions:
Applications.Authentications.Host.Get

Host.Startup: Information: Job host started
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:...
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:...
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
Microsoft.Hosting.Lifetime: Information: Content root path: ...\bin\Debug\net6.0
Host.Triggers.Queue: Warning: Message has reached MaxDequeueCount of 5. Moving message to queue 'queue-poison'.
```

#### Expected behavior

Works like `beta.1` :P

#### Actual behavior

Broken.

#### Known workarounds

Revert back to `beta.1`.

#### Related information 

To be certain, the above references this package:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage

Everything else has been great until this. :)

**Comment by v-anvari** [comment]
Hi @Mike-E-angelo ,The Stable version is 4.0.4. Are you seeing the error only on the beta versions?

Edit: But, I also see that the support for queues extends till beta.5. Microsoft.Azure.WebJobs.Extensions.Storage.Queues (>= 5.0.0-beta.5).

This shall require further investigation. Could we have the repro steps. Can you also share the Function invocation id caused during the error, Time stamp and the region.

**Comment by Mike-E-angelo** [comment]
Thank you for your reply @v-anvari.  I do not believe I ever used the stable version, or if I did there was something about the beta that was required.  Not sure, it was a long time ago. 😁

I did a little more digging for you and it appears that this started in `beta.2`.  Additionally, I am now seeing exception messages where before I did not.  It appears this is due to processing `UTF-8` messages as opposed to `Base64`.

Here is the stack trace:

```
fail: Function.ProcessQueueMessage[3]
      Executed 'Functions.ProcessQueueMessage' (Failed, Id=5acae3c7-14e9-4685-a823-93bf24dab024, Duration=3ms)
      Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage
       ---> System.InvalidOperationException: Exception binding parameter 'message'
       ---> System.Text.DecoderFallbackException: Unable to translate bytes [C7] at index 1 from specified code page to Unicode.
         at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
         at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
         at System.Text.Encoding.GetCharCountWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, DecoderNLS decoder)
         at System.Text.Encoding.GetCharCountWithFallback(Byte* pBytesOriginal, Int32 originalByteCount, Int32 bytesConsumedSoFar)
         at System.Text.UTF8Encoding.GetCharCount(Byte* bytes, Int32 count)
         at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
         at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Common.BinaryDataExtensions.ToValidUTF8String(BinaryData binaryData)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Triggers.StorageQueueMessageToStringConverter.Convert(QueueMessage input)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Triggers.ConverterArgumentBindingProvider`1.ConverterArgumentBinding.BindAsync(QueueMessage value, ValueBindingContext context)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Triggers.QueueTriggerBinding.BindAsync(Object value, ValueBindingContext context)
         at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync(ValueBindingContext context, Object value, IDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 56
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DelayedException.cs:line 27
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.PrepareParametersAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 888
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 466
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 326
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 94
fail: Host.Results[0]
      Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage
       ---> System.InvalidOperationException: Exception binding parameter 'message'
       ---> System.Text.DecoderFallbackException: Unable to translate bytes [C7] at index 1 from specified code page to Unicode.
         at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
         at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
         at System.Text.Encoding.GetCharCountWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, DecoderNLS decoder)
         at System.Text.Encoding.GetCharCountWithFallback(Byte* pBytesOriginal, Int32 originalByteCount, Int32 bytesConsumedSoFar)
         at System.Text.UTF8Encoding.GetCharCount(Byte* bytes, Int32 count)
         at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
         at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Common.BinaryDataExtensions.ToValidUTF8String(BinaryData binaryData)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Triggers.StorageQueueMessageToStringConverter.Convert(QueueMessage input)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Triggers.ConverterArgumentBindingProvider`1.ConverterArgumentBinding.BindAsync(QueueMessage value, ValueBindingContext context)
         at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Triggers.QueueTriggerBinding.BindAsync(Object value, ValueBindingContext context)
         at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync(ValueBindingContext context, Object value, IDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 56
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DelayedException.cs:line 27
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.PrepareParametersAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 888
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 466
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 326
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 94
```

A project with the minimal reproduction can be found here:
https://github.com/Mike-E-angelo/Stash/tree/master/Azure.BrokenBeta

**Comment by v-anvari** [comment]
Thank you for the information, we shall investigate this further and update as appropriate

**Comment by Mike-E-angelo** [comment]
Great, thank you @v-anvari!

**Comment by v-anvari** [comment]
Hi @Mike-E-angelo , There were different issues raised on the beta versions. Now when I try to reproduce the issue, I don't see the beta versions in the local development. Let me know if you are able to see the release versions. 

![image](https://user-images.githubusercontent.com/66122429/132247045-c1f64c51-8726-4bae-b40b-817671fc24af.png)

**Comment by Mike-E-angelo** [comment]
Don't forget to `Include prerelease`, @v-anvari. :)

![](https://i.imgur.com/zLre4Er.png)

**Comment by v-anvari** [comment]
Apologies, Thank you for the information, I am able to reproduce the issue, I shall discuss this issue internally and update as appropriate

**Comment by v-anvari** [comment]
Hi @kasobol-msft , Tagging for further investigation. We have a repro with this issue, can you kindly take a look.

FYI - @fabiocav

**Comment by kasobol-msft** [comment]
Please see https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/CHANGELOG.md#500-beta2-2021-02-09 .

**Comment by v-anvari** [comment]
Thank you for the information

**Comment by Mike-E-angelo** [comment]
Indeed, this issue is a lot easier to accept/understand now that there are exception messages being thrown.  When I first encountered it, there were zero exceptions being emitted to the console/logging and it was incredibly perplexing.  I am not sure if that was a transient issue w/ VS2019 or what.  In any case, this makes sense now and kudos for putting the notes in the `CHANGELOG`. 👍  

Closing this now as it is known/expected behavior in `beta.2+`.

**Comment by Mike-E-angelo** [comment]
Hi All, me again. 😁

I am looking into this now, and the suggested configuration appears to be for `host.json`.  In my case, I do not have a `host.json` in my application which is a Console Application working as a WebJob and not an Azure Function (where it seems `host.json` is used, based on searching).  I have been spending the past hour attempting to search for how to apply `host.json` configuration to a Console Application but am having trouble finding this.

FWIW I did try adding a `host.json` to my Console Application but this appears to be ignored (and/or additional action is required).

Any pointers would be greatly appreciated.  For the interim, I am hardcoding the configuration at runtime, which works.  However, it would be ideal to have this in the configuration where it belongs.  Thank you for any continued assistance you can provide.

**Comment by kasobol-msft** [comment]
@Mike-E-angelo  You can call https://github.com/Azure/azure-sdk-for-net/blob/7583626ea7f12e801002febe185ab719a94c14dc/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/src/StorageQueuesWebJobsBuilderExtensions.cs#L29 programatically when you build webjobs host.

**Comment by Mike-E-angelo** [comment]
Thank you for your suggestion @kasobol-msft it is appreciated.  That's actually what I am currently doing and what I referenced to earlier with "hardcoding" the configuration.  Is there no way to apply this configuration via a file for Console Applications?

**Comment by kasobol-msft** [comment]
I can't see an easy way to achieve that other than read a file before you configure host and use values from the file in the `Action<QueuesOptions>`

**Comment by Mike-E-angelo** [comment]
Bummer @kasobol-msft.  Thank you for taking the time to relay the bad news.  It's very surprising/disappointing that this does not exist but I will work with the hardcoding for now.  I do appreciate your efforts out there as well as taking the time to assist. 👍
