### ISSUE TITLE
The host has not yet started

### ISSUE THREAD

**Issue by JuanFaustino** [Azure/azure-webjobs-sdk#2793]
I create new simple Azure LogicApps Standard following https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#webhook-setup.

Azure Blob Service is running sucessfully and when press F5, I receive this error:
Azure Functions Core Tools
Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0

[2021-11-29T21:42:05.409Z] Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow 'Stateful1' validate and create workflow failed, the error is 'Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.'', exception='Microsoft.WindowsAzure.Storage.StorageException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.

I missing something, please help me.

My host.json file:
```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    }
}
```

My local.settings.json file:
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "WORKFLOWS_TENANT_ID": "e7e3deda-f62b-44f1-bf7a-f2a73e749546",
    "WORKFLOWS_SUBSCRIPTION_ID": "2c495b46-b29b-4297-99b8-80d327876d69",
    "WORKFLOWS_RESOURCE_GROUP_NAME": "rg-bhs-eus2-dev-sc-logicapps",
    "WORKFLOWS_LOCATION_NAME": "eastus2",
    "WORKFLOWS_MANAGEMENT_BASE_URI": "https://management.azure.com/",
    "Workflows.WebhookRedirectHostUri": "http://localhost:7071" //I tried ngrok link and receive same error.
  },
  "Host": {
    "LocalHttpPort": 7071,
    "CORS": "*",
    "CORSCredentials": false
  }
}
```

My workflow.json file:
```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "http",
                "inputs": {
                    "statusCode": 200,
                    "body": {
                        "Message": "hello"
                    }
                },
                "runAfter": {}
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```

**Comment by v-bbalaiagar** [comment]
Hi @JuanFaustino, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by sven5** [comment]
same issue here
![image](https://user-images.githubusercontent.com/8734624/145839948-469e8588-2b79-4cca-bcc7-a254505e742e.png)

Beginning of StackTrace:

```
Azure Functions Core Tools
Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0

[2021-12-13T15:27:14.488Z] Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow 'ImportOffersLegacy' validate and create workflow failed, the error is 'Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.'', exception='Microsoft.WindowsAzure.Storage.StorageException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
[2021-12-13T15:27:14.491Z]  ---> System.Net.Http.HttpRequestException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
[2021-12-13T15:27:14.492Z]  ---> System.Net.Sockets.SocketException (10061): Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
[2021-12-13T15:27:14.492Z]    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
[2021-12-13T15:27:14.493Z]    --- End of inner exception stack trace ---
[2021-12-13T15:27:14.494Z]    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
[2021-12-13T15:27:14.494Z]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
[2021-12-13T15:27:14.495Z]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2021-12-13T15:27:14.496Z]    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2021-12-13T15:27:14.496Z]    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
[2021-12-13T15:27:14.497Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Http.HttpWebRequestProcessor.SendWithHttpClient(HttpWebRequest webRequest, MemoryStream content, CancellationToken cancellationToken)
[2021-12-13T15:27:14.498Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Http.HttpWebRequestProcessor.SendWithHttpClient(HttpWebRequest request, TimeSpan timeout, MemoryStream content)

[2021-12-13T15:27:14.499Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Storage.FastCloudStorageClientExecutor.Attempt(OperationContext operationContext, FastCloudStorageExecutionContext executionContext, MemoryStream content)
```

**Comment by sven5** [comment]
Ok, I have the solution, it's easy, you just have to run all Azurite services.
In VSCode - hit F1 - type **Azurite: Start**

**Comment by JuanFaustino** [comment]
Thanks a lot Sven. It is works.

**Comment by faelpinho** [comment]
> In VSCode - hit F1 - type **Azurite: Start**

How can I start Azurite using Visual Studio 2022?
I'm getting the same error here...

**Comment by oiluis** [comment]
any news here @faelpinho  or others? I am having the same issue ...
