### ISSUE TITLE
BindingDataProvider.FromType Fails to Resolve Shadowed Properties

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-webjobs-sdk#2830]
When a trigger binds to a type that shadows a base class property, the call to `BindingTypeProvider.FromType` fails with:

**Error Message:**
```text
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method '[[ METHOD ]]'
----> System.InvalidOperationException : Multiple properties named '[[ PROPERTY ]]' found in type '[[ TYPE ]]'.
```

**Stack Trace:**
```text
--InvalidOperationException
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingDataProvider.FromType(Type type) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingDataProvider.cs:line 103
   at Microsoft.Azure.WebJobs.Host.Triggers.CustomTriggerArgumentBinding`2..ctor(ITriggerBindingStrategy`2 bindingStrategy, IConverterManager converterManager, FuncAsyncConverter converter, Type userType) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\CustomTriggerArgumentBinding.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingFactoryHelpers.GetDirectTriggerBindingWorker[TMessage,TTriggerValue](ITriggerBindingStrategy`2 bindingStrategy, IConverterManager converterManager, Type userType) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingFactoryHelpers.cs:line 42
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingFactoryHelpers.GetDirectTriggerBinding[TMessage,TTriggerValue](Type exactType, ITriggerBindingStrategy`2 bindingStrategy, IConverterManager converterManager) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingFactoryHelpers.cs:line 30
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingFactoryHelpers.GetTriggerArgumentElement
```

When `FromType` processes properties of the target type returned by `PropertyHelper.GetProperties(type)`, it adds them to a dictionary in the order that they're returned, failing by design if there are any duplicate names  _([src](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingDataProvider.cs#L91-L108))_: 

```csharp
// The properties on user-defined types are valid binding data.
IReadOnlyList<PropertyHelper> bindingDataProperties = PropertyHelper.GetProperties(type);
if (bindingDataProperties.Count == 0)
{
    return null;
}

Dictionary<string, Type> contract = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);
foreach (PropertyHelper property in bindingDataProperties)
{
    if (contract.ContainsKey(property.Name))
    {
        throw new InvalidOperationException(
            string.Format(CultureInfo.InvariantCulture,
            "Multiple properties named '{0}' found in type '{1}'.", property.Name, type.Name));
        }
        contract.Add(property.Name, property.Property.PropertyType);
    }
}
```

This disallows binding to types with properties that shadow a base class member.

## Repro steps

- Create a function that references the `Microsoft.Azure.WebJobs.Extensions.EventHubs` v5.x+ and the latest nightly build of `Azure.Messaging.EventHubs`  from the [Azure SDK development package feed](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed).

- Create a function with an Event Hubs trigger, such as:
```csharp
public static void ProcessMultipleEvents([EventHubTrigger(TestHubName, Connection = TestHubName)] EventData[] events)
{
    // Code
}
```

- Observe the exception due to the new hierarchy for `EventData` where property shadowing is used:

**EventData** _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/EventData.cs))_

```csharp
public class EventData : MessageWithMetadata
{
    public new string ContentType { get;  set; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    protected override ContentType? ContentTypeCore
    {
        get => new ContentType(ContentType);
        set => ContentType = value.ToString();
    }
}
```

**MessageWithMetadata**  _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.Experimental/src/MessageWithMetadata.cs))_

```csharp
public class MessageWithMetadata
{
    public virtual ContentType? ContentType
    {
        get => ContentTypeCore;
        set => ContentTypeCore = value;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    protected virtual ContentType? ContentTypeCore { get; set; }
}
```

## Expected behavior

The binding succeeds by selecting the property declared on the type being bound rather than giving equal consideration to properties deeper in the hierarchy.   In this case, the `ContentType` property from `EventData` should have been selected and the property from the base class ignored.

## Actual behavior

**Error Message**
```text
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'EventHubTestInitialOffsetFromEnqueuedTimeJobs.ProcessMultipleEvents'
----> System.InvalidOperationException : Multiple properties named 'ContentType' found in type 'EventData'.
```

**Stack Trace**
```text
at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 81
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 94
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 97
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.GetAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 69
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.Create(JobHost host, CancellationToken shutdownToken, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostContextFactory.cs:line 119
   at Microsoft.Azure.WebJobs.JobHost.InitializeHostAsync(CancellationToken cancellationToken, TaskCompletionSource`1 initializationTask) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 347
   at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 95
   at Microsoft.Azure.WebJobs.Host.EndToEndTests.WebJobsEventHubTestBase.BuildHost[T](Action`1 configurationDelegate, Action`1 preStartCallback) in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/WebJobsEventHubTestBase.cs:line 92
   at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_InitialOffsetFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 411
   at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_InitialOffsetFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 430
   at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_InitialOffsetFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 430
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
--InvalidOperationException
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingDataProvider.FromType(Type type) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingDataProvider.cs:line 103
   at Microsoft.Azure.WebJobs.Host.Triggers.CustomTriggerArgumentBinding`2..ctor(ITriggerBindingStrategy`2 bindingStrategy, IConverterManager converterManager, FuncAsyncConverter converter, Type userType) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\CustomTriggerArgumentBinding.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingFactoryHelpers.GetDirectTriggerBindingWorker[TMessage,TTriggerValue](ITriggerBi
```

## Proposed fix

Update `BindingDataProvider.FromType` on [L99](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingDataProvider.cs#L99) to consider the type declaring the property.  If a property is declared on the `type` parameter directly, remove other members discovered lower in the hierarchy.  Throw only when there is a naming conflict and the property does not exist directly on `type`.

## Related information 

This behavior can be observed running [tests](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests) for the `Microsoft.Azure.WebJobs.Extensions.EventHubs` package from the [Azure SDK for .NET](https://github.com/Azure/azure-sdk-for-net) repository.

**Comment by jsquire** [comment]
//fyi:  @joshlove-msft

**Comment by JoshLove-msft** [comment]
Agree with this proposal - I think it would make sense to defer to the property that is on the specific type that the user is binding to, so in this case we would use EventData.ContentType and ignore the property from the base type.

**Comment by fabiocav** [comment]
No objections from me on this either. The proposal sounds reasonable.

@jsquire are you planning on sending a PR on this, or would you like us to assign on our end?

@mathewc wanted to tag you so you could share your thoughts on this as well.

**Comment by jsquire** [comment]
@fabiocav:  We're happy to submit a PR, though we'll likely need guidance on how to validate the impact to the wider ecosystem.

**Comment by jsquire** [comment]
@mathewc:  Do you have any concerns or feedback on the proposed approach?   I'd like to dig into this early next week if not.

**Comment by jsquire** [comment]
Fixed by: #2831

**Comment by andyhammar** [comment]
Hi
We're hitting this after upgrading to latest VS (17.2.0) that was just released.
If I understand correctly, this is the part of the host runtime - is there release of the func runtime that needs to happen?
Sorry if I'm misunderstanding how these things relate.

Thanks!
@mathewc @jsquire 

```
Azure Functions Core Tools
Core Tools Version:       4.0.4483 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473                      
```

![image](https://user-images.githubusercontent.com/1713268/167995074-19ba8271-704f-44d6-91ed-2cab625ebc04.png)

**Comment by mathewc** [comment]
The WebJobs SDK fix (SDK package version 3.0.33) is in Functions Host version 4.2.0. This version of core tools is on 4.1.3.17473. So we're waiting on a new Core Tools release with the updated host version with the fix.

**Comment by andyhammar** [comment]
Thanks for the quick reply @mathewc !
And looking at the [core tools releases](https://github.com/Azure/azure-functions-core-tools/releases) page, release cadence is monthly so the next release is end of May roughly?

And those core tools will then be in the next VS release?

My best bet now in your opinion? Uninstall VS and reinstall 17.1.x ? Thanks!

**Comment by mathewc** [comment]
The new tools version is in testing now and will hopefully be released by mid next week. You'll then be able to update just the tools - no VS update needed.

**Comment by ThomasVandenbon** [comment]
@mathewc I've tried to update only the tools, but I'd like this upgrade to be picked up by Visual Studio too.
What's the procedure to update the tools in such a way that Visual Studio will also use the latest version?
Is there some documentation for this?

**Comment by mathewc** [comment]
If you update the core tools as per doc [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools) both command line and VS will be updated. I just updated myself and verified that the new version 4.0.4590 has these changes.

**Comment by ThomasVandenbon** [comment]
@mathewc 
I had used npm to update my version as described [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#changing-core-tools-versions), which had no effect.

I've now used the Windows installer (MSI) (from [the link you provided](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools)) and this does work.

Thank you! 👍
