### ISSUE TITLE
BlobClient.DeleteIfExists() results in Host.FunctionInvocationException InvalidCastException: 'System.DateTimeOffset' to type 'System.DateTime'

### ISSUE THREAD

**Issue by fartwhif** [Azure/azure-webjobs-sdk#2833]
While deployed as a WebJob to Azure, whenever attempting to call "BlobClient.DeleteIfExists" an exception is thrown instead.  The following is the stack trace followed by the truncated caller function

```
[02/21/2022 22:48:13 > 4160e6: INFO] info: Function.BlobTriggerCSharp.User[0]
[02/21/2022 22:48:13 > 4160e6: INFO]       Completed proceccing, took 00:00:13.5652762, deleting DataSync package C___TEMP__f50a5a0b2c4146b6bd5ad845a3b0f2e9.tmp.zip
[02/21/2022 22:48:13 > 4160e6: INFO] fail: Function.BlobTriggerCSharp[3]
[02/21/2022 22:48:13 > 4160e6: INFO]       Executed 'BlobTriggerCSharp' (Failed, Id=a0fc81ef-5766-48e0-a6cc-8dd3d85cf3fb, Duration=13610ms)
[02/21/2022 22:48:13 > 4160e6: INFO]       Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: BlobTriggerCSharp
[02/21/2022 22:48:13 > 4160e6: INFO]        ---> System.InvalidCastException: Unable to cast object of type 'System.DateTimeOffset' to type 'System.DateTime'.
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
[02/21/2022 22:48:13 > 4160e6: INFO]          at lambda_method98(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
[02/21/2022 22:48:13 > 4160e6: INFO]          at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[02/21/2022 22:48:13 > 4160e6: INFO]          at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[02/21/2022 22:48:13 > 4160e6: INFO]          at BackgroundTasks.Functions.RunAsync(Stream DataSyncPackage, BlobClient client, String name, ILogger log) in C:\projects\git\clients\Quality Labor Management\PunchClock\BackgroundTasks\Program.cs:line 82
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 514
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296
[02/21/2022 22:48:13 > 4160e6: INFO]          --- End of inner exception stack trace ---
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105
[02/21/2022 22:48:13 > 4160e6: INFO] fail: Host.Results[0]
[02/21/2022 22:48:13 > 4160e6: INFO]       Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: BlobTriggerCSharp
[02/21/2022 22:48:13 > 4160e6: INFO]        ---> System.InvalidCastException: Unable to cast object of type 'System.DateTimeOffset' to type 'System.DateTime'.
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
[02/21/2022 22:48:13 > 4160e6: INFO]          at lambda_method98(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
[02/21/2022 22:48:13 > 4160e6: INFO]          at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[02/21/2022 22:48:13 > 4160e6: INFO]          at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[02/21/2022 22:48:13 > 4160e6: INFO]          at BackgroundTasks.Functions.RunAsync(Stream DataSyncPackage, BlobClient client, String name, ILogger log) in C:\projects\git\clients\Quality Labor Management\PunchClock\BackgroundTasks\Program.cs:line 82
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 514
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296
[02/21/2022 22:48:13 > 4160e6: INFO]          --- End of inner exception stack trace ---
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343
[02/21/2022 22:48:13 > 4160e6: INFO]          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105
```

```
 [FunctionName("BlobTriggerCSharp")]
        public static async Task RunAsync(
            [BlobTrigger(Constants.DataSyncBlobContainerName + "/{name}")] Stream DataSyncPackage,
            [Blob(Constants.DataSyncBlobContainerName + "/{name}")] BlobClient client,
            string name, ILogger log)
        {
//...
// this appears in the log
                    log.LogInformation($"Completed processing, took {sw1.Elapsed}, deleting DataSync package {name}");
//...
// i think this throws the exception, the next log message is the exception and the blob remains in the queue
                client.DeleteIfExists();
//...
        }
```

#### Repro steps

Provide the steps required to reproduce the problem

upload a blob

trigger a function

delete the blob

#### Expected behavior

the blob is deleted

#### Actual behavior

the blob remains in queue, an exception is thrown and logged

#### Known workarounds

none discovered as of yet

#### Related information 

Only throws the exception when deployed to Azure, running the WebJob locally does not invoke the exception and instead the blob is deleted from the queue as expected.

Microsoft.Azure.WebJobs 3.0.31
Microsoft.Azure.WebJobs.Extensions 4.0.1

**Comment by v-bbalaiagar** [comment]
Hi @fartwhif , Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by fartwhif** [comment]
I deleted and then republished the WebJob and it seems to have fixed the issue.  triggered function and the call within it to BlobClient.DeleteIfExists are working again.

**Comment by v-bbalaiagar** [comment]
Hi @fartwhif , Let us know if you have any further queries regarding this issue so that we can investigate this further.
