### ISSUE TITLE
Templated ServiceBusTrigger QueueName fails to resolve in 3.0.30

### ISSUE THREAD

**Issue by MikeWilliams-UK** [Azure/azure-webjobs-sdk#2843]
Templated ServiceBusTrigger QueueName fails to resolve in 3.0.30

Defining a Service bus trigger as `Listen([ServiceBusTrigger("%QueueName%", Connection = "ServiceBusConnection")]` fails to resolve the `QueueName` when running in Azure

Add a setting in local.settings.json settings file for QueueName , e.g. "QueueName": "dev-queue"
Add a setting in Azure as show below
![image](https://user-images.githubusercontent.com/13162784/159034296-48518b4d-9cdc-4fcc-baba-77893639c7f1.png)

Set the ServiceBusTriggerAttribute to use the templated value, e.g. [ServiceBusTrigger("%QueueName%")]

Expected behavior
Prior to 3.0.*, the queue trigger would pick up the queue name from the local.settings.json settings appSettings or the Azure Function's settings

Actual behavior
Setting is only picked up when running locally in Visual Studio
When running in Azure I get a run an exception (when logs viewed using KuDu):
```
2022-03-18T14:20:14.596 [Information] Starting JobHost
2022-03-18T14:20:14.598 [Information] Starting Host (HostId=telemetrymover20220318154415, InstanceId=0705eec1-45cd-4c00-89c6-ca53a9d4a7ce, Version=4.1.3.17473, ProcessId=5588, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~4)
2022-03-18T14:20:14.621 [Information] Loading functions metadata
2022-03-18T14:20:14.658 [Information] 1 functions loaded
2022-03-18T14:20:14.726 [Information] Generating 1 job function(s)
2022-03-18T14:20:14.786 [Error] Error indexing method 'Listener'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Listener' ---> System.InvalidOperationException : '%QueueName%' does not resolve to a value.
   at Microsoft.Azure.WebJobs.Host.NameResolverExtensions.ResolveWholeStringCore(INameResolver resolver,String resolve,Boolean throwOnFailure) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\NameResolverExtensions.cs : 96
   at Microsoft.Azure.WebJobs.ServiceBus.Triggers.ServiceBusTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 149
   End of inner exception
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 157
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 85
2022-03-18T14:20:14.848 [Error] Microsoft.Azure.WebJobs.Host: Error indexing method 'Listener'. Microsoft.Azure.WebJobs.Host: '%QueueName%' does not resolve to a value.
2022-03-18T14:20:14.974 [Warning] Function 'Listener' failed indexing and will be disabled.
2022-03-18T14:20:14.976 [Warning] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

```

**Comment by mathewc** [comment]
In the latest logs for your app (from 3/18) I see the below error. So it looks like it is looking for environment setting **ServiceBusSettings:QueueName**. Can you double check your function method definition and share what value you're passing to the ServiceBusTriggerAttribute? Also check in Kudu environment explorer that an app setting with this name exists.

`Microsoft.Azure.WebJobs.Host: Error indexing method 'Listener'. Microsoft.Azure.WebJobs.Host: '%ServiceBusSettings:QueueName%' does not resolve to a value.`

**Comment by MikeWilliams-UK** [comment]
Sorry about that I initially copied the wrong portion of the log file from KuDu

I have tried both %QueueName% and %ServiceSettings:QueueName% as it was suggested in a post I saw on the internet.
This worked fine with V1 of the SDK, I never got round to updating to V2, so I am trying to go straight to V3

I thought I had edited the description to rationalise the logs to say %QueueName%

For now I have hard coded my queue name and deployed with that, but I feel that this is a hack.

**Comment by MikeWilliams-UK** [comment]
It seems to be closely related to https://github.com/Azure/azure-webjobs-sdk/issues/2063

**Comment by MikeWilliams-UK** [comment]
Here is a screen shot from Kudu showing the app's settings
![image](https://user-images.githubusercontent.com/13162784/159042258-6666dd26-5e2c-4a4e-a84a-d68370caee65.png)

**Comment by MikeWilliams-UK** [comment]
This was my function deinition (before I hard coded the queue name)

![image](https://user-images.githubusercontent.com/13162784/159042635-98b8a4d7-e0c2-46a6-a754-a055118b63c5.png)

**Comment by MikeWilliams-UK** [comment]
I even tried using QueueName raw without % wrappers with no success

**Comment by MikeWilliams-UK** [comment]
I am using VS2022 17.1.1 now, the service was probaly templated with an earlier revision of VS if that makes any difference.

**Comment by MikeWilliams-UK** [comment]
Here are the NuGet packages I have installed
![image](https://user-images.githubusercontent.com/13162784/159044732-bc6e7647-1fab-42f5-9091-0c2f9e277ac9.png)

**Comment by mathewc** [comment]
I'm unable to repro this. I'm using VS 17.1.1, and the same package versions as you above:

![image](https://user-images.githubusercontent.com/1056548/159083095-f4bdab9a-49b5-4999-a9ee-c7ed9d1969e1.png)

My code:

```csharp
public static class Function1
{
    [FunctionName("Function1")]
    public static void Run([ServiceBusTrigger("%QueueName%", Connection = "ServiceBusConnection")] string myQueueItem, ILogger log)
    {
        log.LogInformation($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
    }
}
```

This works for me locally as well as deployed, as long as I have QueueName and ServiceBusConnection settings in local.settings.json and portal app settings respectively.

**Comment by MikeWilliams-UK** [comment]
Thanks for your help.
I have re-built it from scratch again and it is now working with no obvious code changes ???

I am extracting more information especially the userProperties. I did wonder if this was the difference, but this too is working fine.
```csharp
public static class Function1
{
    [FunctionName("Function1")]
    public static void Run([ServiceBusTrigger("%QueueName%", Connection = "ServiceBusConnection")]
        string messageBody,
        DateTime enqueuedTimeUtc,
        long sequenceNumber,
        ExecutionContext context,
        IDictionary<string, object> userProperties,
        ILogger log)
    {
        log.LogInformation($"Message #{sequenceNumber} Body: {messageBody}");
    }
}
```
