### ISSUE TITLE
BlobTrigger - UserManagedIdentity - Function host is stopping

### ISSUE THREAD

**Issue by tsbala** [Azure/azure-webjobs-sdk#2921]
I am getting an `AuthorizationFailure` on a Blob Trigger function using v5.0.0 of the `Microsoft.Azure.WebJobs.Extensions.Storage.Blobs` package.

I have a BlobTrigger that is using a user assigned identity connection. I have deployed the Function App to Azure and the Azure function Host runtime crashes with the following exception and stack trace

```
2022-09-29T19:27:03.861 [Error] An unhandled exception has occurred. Host is shutting down.
Azure.RequestFailedException : This request is not authorized to perform this operation.
RequestId:10899e39-a01e-0156-2d39-d4b271000000
Time:2022-09-29T19:27:03.3840337Z
Status: 403 (This request is not authorized to perform this operation.)
ErrorCode: AuthorizationFailure

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:10899e39-a01e-0156-2d39-d4b271000000
Time:2022-09-29T19:27:03.3840337Z</Message></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 10899e39-a01e-0156-2d39-d4b271000000
x-ms-client-request-id: 9f88002e-45d3-48a8-83f3-bed7952bdda2
x-ms-error-code: AuthorizationFailure
Date: Thu, 29 Sep 2022 19:27:02 GMT
Content-Length: 246
Content-Type: application/xml

   at async Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegmentAsync(String prefix,String marker,Nullable`1 maxresults,IEnumerable`1 include,Nullable`1 timeout,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker,BlobTraits traits,BlobStates states,String prefix,Nullable`1 pageSizeHint,Boolean async,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken,Nullable`1 pageSizeHint,Boolean async,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.AsPages[T](String continuationToken,Nullable`1 pageHintSize)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.AsPages[T](String continuationToken,Nullable`1 pageHintSize)
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.PollNewBlobsAsync(BlobContainerClient container,ContainerScanInfo containerScanInfo,String clientRequestId,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.PollAndNotify(BlobContainerClient container,ContainerScanInfo containerScanInfo,List`1 failedNotifications,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken)
2022-09-29T19:27:03.947 [Information] Stopping JobHost
2022-09-29T19:27:03.947 [Information] Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.CompositeListener' for function 'BlobEventPublisher'
```

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a .NET function app C# project. Choose .NET 6.0 as the language and version. 

2. The code in the function app is as follows
```csharp
    [FunctionName("BlobEventPublisher")]
    public async Task Run(
        [BlobTrigger("%TenantStorageContainer%/{fileNameWithoutExtension}" + _fileExtension, Connection = "TenantStorageAccountConnection")]
        Stream blob,
        string fileNameWithoutExtension)
    {
        using var reader = new StreamReader(blob);
        var text = await reader.ReadToEndAsync();
        await _busMessageSender.SendMessage("sbq-rp-inbox", new text);
    }
```
It is a simple Blob trigger function that reads the content of the blob and publishes it to a service bus queue.

3. Create a Function App in Azure, using a S1 Linux plan.

4. Create a User Assigned Identity and assign it to the Function App.

5. Assign the `Storage Blob Data Owner`, `Storage Blob Queue Contributor` and `Owner` roles to the User Assigned Identity for the Function App storage account.

6. Create a Storage V2 Storage account for the BlobTrigger.

7. Create a container in it called `Receive`.

8. Assign the `Storage Blob Data Owner`, `Storage Blob Queue Contributor` and `Owner` roles to the User Assigned Identity for the BlobTrigger Connection storage account.

9. Enable the managed identity for the default `AzureWebJobsStorage` connection in the Function App's configuration by setting `AzureWebJobsStorage__accountName` to the Function App storage account name. 

10. Enables the managed identity for the BlobTrigger storage account connection by setting the following in the Function App's configuration

| Setting | Value  |
|-------------------------------------------------|-----------------------------------------------|
| TenantStorageAccountConnection__blobServiceUri  | https://{account name}.blob.core.windows.net  |
| TenantStorageAccountConnection__queueServiceUri  | https://{account name}.queue.core.windows.net  |
| TenantStorageAccountConnection__credential      | managedidentity                               |
| TenantStorageAccountConnection__clientId        | {useridentity.clientid}                       |

#### Expected behavior

The Function App Host should startup and the BlobTrigger function should be triggered when a file is dropped in the container.

#### Actual behavior

The Function App Host starts up and crashes after some time. The docker logs report the app is not healthy and the host is shutdown

```
2022-09-29T20:36:02.285Z INFO  - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2022-09-29T20:36:06.088Z INFO  - Initiating warmup request to container app-ap-ndc-tc1-tms-rp-northeurope6eed0f46_1_61c6c775_msiProxy for site app-ap-ndc-tc1-tms-rp-northeurope6eed0f46
2022-09-29T20:36:06.163Z INFO  - Container app-ap-ndc-tc1-tms-rp-northeurope6eed0f46_1_61c6c775_msiProxy for site app-ap-ndc-tc1-tms-rp-northeurope6eed0f46 initialized successfully and is ready to serve requests.
2022-09-29T20:36:06.164Z INFO  - Initiating warmup request to container app-ap-ndc-tc1-tms-rp-northeurope6eed0f46_1_61c6c775 for site app-ap-ndc-tc1-tms-rp-northeurope6eed0f46
2022-09-29T20:36:21.722Z INFO  - Waiting for response to warmup request for container app-ap-ndc-tc1-tms-rp-northeurope6eed0f46_1_61c6c775. Elapsed time = 15.6340194 sec
2022-09-29T20:36:24.225Z INFO  - Container app-ap-ndc-tc1-tms-rp-northeurope6eed0f46_1_61c6c775 for site app-ap-ndc-tc1-tms-rp-northeurope6eed0f46 initialized successfully and is ready to serve requests.
2022-09-29T20:36:39.288Z ERROR - Container for app-ap-ndc-tc1-tms-rp-northeurope6eed0f46_1_61c6c775 site app-ap-ndc-tc1-tms-rp-northeurope6eed0f46 is unhealthy, Stopping site.
2022-09-29T20:36:39.289Z INFO  - Stopping site app-ap-ndc-tc1-tms-rp-northeurope6eed0f46 because it is not healthy.
```

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* ```<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Blobs" Version="5.0.0" />```

**Comment by ramya894** [comment]
@tsbala Please go through the below links for more information on usermanagedidentity configuration.
https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2
https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#configure-an-identity-based-connection
If the issue is still there, please provide us the function app name, invocation id and timestamp details to investigate it further.

**Comment by tsbala** [comment]
@ramya894 thanks for the links. I have checked the configuration for usermanagedidentity and the role assignments are correct. 

We then assigned the user managed identity the role of `Storage Account Contributor` on the `AzureWebJobsStorage` storage account and this fixed the issue.

To recap the user assigned managed identity has been given the following roles on the `AzureWebJobsStorage` storage account and this seems to work.

Role
:-- | 
`Storage Account Contributor` |
`Storage Blob Data Owner` |
`Storage Queue Data Contributor` |

Would be good if you could point us in the direction of any documentation that clearly explains this with respect to usermangedidentity. I was lucky to stumble across the correct roles that were needed to get it working.

**Comment by ramya894** [comment]
@tsbala Please follow the below documentation for Managed identities.
https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp

**Comment by tsbala** [comment]
@ramya894 can you please point me to relevant bit in the document that explains what roles are needed for user assigned identities in a BlobTrigger? The only thing I could find was the assigning a user assigned identity via the portal.
