### ISSUE TITLE
Webjob throws a TypeInitializationException during startup

### ISSUE THREAD

**Issue by shadowano** [Azure/azure-webjobs-sdk#3041]
I have webjobs written in .NET Framework 4.7.2 that have lived for years, and have this week upgraded them to use latest Azure.Storage.* nuget packages instead of WindowsAzure.Storage. I have also removed a lot of unused deprecated Microsoft.AspNetCore.* packages in my webjobs. 

Even before I did the upgrades above, I get the following error in console during startup of my webjobs:
```
Unexpcted Exception During Runtime Startup:
System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load while attempting to initialize the default appdomain.
 ---> System.Runtime.InteropServices.COMException: Invalid operation. (Exception from HRESULT: 0x80131022)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at <CrtImplementationDetails>.GetDefaultDomain()
   at <CrtImplementationDetails>.DoCallBackInDefaultDomain(IntPtr function, Void* cookie)
   at <CrtImplementationDetails>.LanguageSupport.InitializeDefaultAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeEnvironment()
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment..cctor()
```
The webjob runs and work just fine even if this exception is thrown during startup. I had this error even before I started upgrading and fixing deprecated nuget packages. 

What causes this exception to be thrown, and how can I fix it?

#### Related information 

Provide any related information 
Microsoft.Azure.WebJobs  3.0.39
Microsoft.Azure.WebJobs.Core 3.0.39
Microsoft.Azure.WebJobs.Extensions 5.0.0
Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.2.0
Microsoft.Azure.WebJobs.Host.Storage 5.0.0

I do **not** have any Microsoft.WindowsAzure* nuget packages installed in my projects.

**Comment by raushan2998** [comment]
Hello @shadowano, Thanks for reporting this.
This error comes from Microsoft.WindowsAzure.ServiceRuntime being loaded, likely via a transitive dependency or old binding redirect. Even if the package isn’t directly referenced, it’s probably still in the build. The exception is non-blocking, but to remove it, you can check for indirect references, clean up config binding redirects, and do a full rebuild after clearing bin/obj.

**Comment by raushan2998** [comment]
Closing the issue as there is no feedback.
