### ISSUE TITLE
[WebjobSDK] EventHub Trigger cannot use Managed Identity.

### ISSUE THREAD

**Issue by Zteat** [Azure/azure-webjobs-sdk#3074]
I'm using Webjob SDK and have a EventHub triggered function. (Not using Function App, just a service using WebJob SDK).
I use the EventHubWebJobsBuilderExtensions.AddEventHubs to inject dependencies EventHub Trigger Attribute may need.
But one of the dependencies is CheckpointClientProvider (StorageClientProvider) could not use Managed Identity, it could only use AzureWebjobStorage connection string (using GetConnectionStringOrSetting in Microsoft.Azure.WebJobs.Extensions.Storage.Queues). Is there any plan to have it support Managed Identity?
[I saw the Function app solution but I'm not using Function app. https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=eventhubs&pivots=programming-language-csharp#configure-an-identity-based-connection]

#### Repro steps

var builder = new HostBuilder();
// Add AzureWebJobsStorage configuration only with Managed Identity Style. No connection string.
builder.ConfigureWebJobs(b =>
{
                    b.AddEventHubs(e =>
                    {
                        e.BatchCheckpointFrequency = 5;
                        e.MaxEventBatchSize = 150;
                        e.PrefetchCount = 512;
                    }).AddAzureStorageBlobs();
}
var host = builder.Build();
host.Run();

Have a function configured with EventHubTrigger attribute.

#### Actual behavior
Exception like below:
**Host run failed: Storage account connection string 'AzureWebJobsStorage' does not exist. Make sure that it is a defined App Setting.,** Microsoft.Azure.WebJobs.Extensions.EventHubs,    at Microsoft.Azure.WebJobs.Extensions.Clients.Shared.StorageClientProvider`2.GetWebJobsConnectionStringSection(String name)
   at Microsoft.Azure.WebJobs.Extensions.Clients.Shared.StorageClientProvider`2.Get(String name)
   at Microsoft.Azure.WebJobs.EventHubs.EventHubClientFactory.GetCheckpointStoreClient()
   at Microsoft.Azure.WebJobs.EventHubs.EventHubTriggerAttributeBindingProvider.<>c__DisplayClass5_0.<TryCreateAsync>b__0(ListenerFactoryContext factoryContext, Boolean singleDispatch)
   at Microsoft.Azure.WebJobs.Host.Triggers.StrategyTriggerBinding`2.CreateListenerAsync(ListenerFactoryContext context) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Triggers\StrategyTriggerBinding.cs:line 67
   at Microsoft.Azure.WebJobs.EventHubs.EventHubTriggerBindingWrapper.CreateListenerAsync(ListenerFactoryContext context)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.ListenerFactory.CreateAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 485
   at Microsoft.Azure.WebJobs.Host.Listeners.HostListenerFactory.CreateAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\HostListenerFactory.cs:line 73
   at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.StartAsyncCore(CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\ListenerFactoryListener.cs:line 45
   at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.StartAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\ShutdownListener.cs:line 29
   at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 99
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

#### Related information 

Provide any related information 

Microsoft.Extensions.Hosting 6.0.0.0
Microsoft.Azure.WebJobs.Extensions.EventHubs 5.3.0.0

**Comment by Zteat** [comment]
Problem solved. Should use : in the configuration instead of __. It works now.
