### ISSUE TITLE
Getting sporadic UnauthorizedAccessException on WebJobsSdk.marker

### ISSUE THREAD

**Issue by Eilon** [Azure/azure-webjobs-sdk#492]
From internal customer:

Sometimes I get bursts of exceptions from my Azure WebJob (which pulls messages from a queue):

```
System.UnauthorizedAccessException: Access to the path 'D:\home\data\jobs\continuous\EventHandler\WebJobsSdk.marker' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.Azure.WebJobs.JobHostConfiguration.WriteSiteExtensionManifest()
   at Microsoft.Azure.WebJobs.JobHostConfiguration..ctor(DefaultStorageAccountProvider storageAccountProvider)
```

I’ve had 7 of these today around 6PM UTC and 2 of these around 4AM UTC on Wednesday.

**Comment by neil-thompson** [comment]
For the record, I am getting these a lot too. 2 instances per slot. One slot (staging)  has the sticky AppSetting "WEBJOBS_STOPPED" = "1" (which might be significant)

**Comment by mathewc** [comment]
This has been *supposedly* fixed multiple times, the latest time by me in this commit (https://github.com/Azure/azure-webjobs-sdk/commit/91da9ad2708d3f856a23db5ac46c37d6598ea09b). The SDK only accesses this file in a single place and we're catching all Access/IO exceptions. Are you sure the error is coming from the SDK? Can you please provide the error details/stack trace? If it's coming from the core WebJobs engine (not SDK) we may need to change something there.

**Comment by neil-thompson** [comment]
I think it might be the engine.
The exception I can see in azure  app diagnostics is:

Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'D:\home\data\jobs\continuous\Listener\WebJobsSdk.marker' is denied.,
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)",
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)",
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)",
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)",
at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)",
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)",
at System.IO.File.WriteAllText(String path, String contents)",
at Microsoft.Azure.WebJobs.JobHostConfiguration.WriteSiteExtensionManifest(),
at Microsoft.Azure.WebJobs.JobHostConfiguration..ctor(DefaultStorageAccountProvider storageAccountProvider),
at Listener.Program.Main()

**Comment by mathewc** [comment]
No, that's coming from the SDK, however that stack trace doesn't exist in the v1.0.1 release. What version are you using - some really old pre-release version? Please confirm you're using v1.0.1 which contains a fix for this which I linked to above.

**Comment by neil-thompson** [comment]
I installed via NuGet 10 days ago - it is the 1.0.0 release.
I can see an update for Microsoft.Azure.Webjobs for 1.0.1 - I'll update my installed version.

So sorry to have wasted your time (and thank you for your help).
