### ISSUE TITLE
TypeLoadException thrown when JobHost stops

### ISSUE THREAD

**Issue by fakedevil** [Azure/azure-webjobs-sdk#564]
I have a webjob which has 3 servicebustrigger. I am noticing that when I stop the webjob, it will trigger a few typeloadexceptions

I am using the following nuget packages:

  <package id="WindowsAzure.ServiceBus" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Web.WebJobs.Publish" version="1.0.3" targetFramework="net451" />
  <package id="Microsoft.Azure.WebJobs" version="1.0.1" targetFramework="net451" />
  <package id="Microsoft.Azure.WebJobs.Core" version="1.0.1" targetFramework="net451" />
  <package id="Microsoft.Azure.WebJobs.ServiceBus" version="1.0.1" targetFramework="net451" />

Let me know if we need other information...
Stack trace below:

System.TypeLoadException: Could not load type 'Microsoft.ServiceBus.Messaging.MessageClientEntity' from assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.<StopAsyncCore>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.StopAsyncCore(CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StopAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StopAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.HeartbeatListener.<StopAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StopAsyncCore>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.Stop()
   at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
   at WebJobs.Program.Main()

**Comment by fakedevil** [comment]
Looks like markdown stripped the packages information. Package information below:

package id="WindowsAzure.ServiceBus" version="3.0.1" targetFramework="net451"
package id="Microsoft.Web.WebJobs.Publish" version="1.0.3" targetFramework="net451"
package id="Microsoft.Azure.WebJobs" version="1.0.1" targetFramework="net451"
package id="Microsoft.Azure.WebJobs.Core" version="1.0.1" targetFramework="net451"
package id="Microsoft.Azure.WebJobs.ServiceBus" version="1.0.1" targetFramework="net451"

**Comment by mathewc** [comment]
The WebJobs SDK relies on ServiceBus package version 2.3.1.0 - it looks like you're pulling in a new major version? We haven't tested the SDK with that version yet, and likely won't move to it until we ourselves increment our major version (to ensure there are no breaking changes that might affect people).

Recommend using the 2.3.1.0 package version and see if you still have this issue.

**Comment by fakedevil** [comment]
I had to move to 2.7.0 due to other dependencies and that seems to be it. No more errors. Thanks!
