### ISSUE TITLE
Using integer with IAsyncCollector fails

### ISSUE THREAD

**Issue by kamranayub** [Azure/azure-webjobs-sdk#585]
Using 1.1.0-beta1

Binding `IAsyncCollector<int>` seems to fail when doing `await queue.AddAsync(someInt)` with:

```
System.ArgumentException: Object serialized to Integer. JObject instance expected.
[10/19/2015 00:05:43 > 144207: INFO]    at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
[10/19/2015 00:05:43 > 144207: INFO]    at Microsoft.Azure.WebJobs.Host.Queues.Bindings.UserTypeToStorageQueueMessageConverter`1.Convert(TInput input)
[10/19/2015 00:05:43 > 144207: INFO]    at Microsoft.Azure.WebJobs.Host.Queues.Bindings.QueueAsyncCollector`1.AddAsync(T item, CancellationToken cancellationToken)
```

**Comment by mathewc** [comment]
Yeah, across the various bindings, IAsyncCollector is designed for complex types, though the documentation isn't clear on that. We might update the bindings to also support simple Types, thought I really think this is a very uncommon scenario.

**Comment by kamranayub** [comment]
Yeah I was confused because a `string` type worked but not an `int` and there was no warning that it would fail until I saw it fail when it was live.

**Comment by mathewc** [comment]
We've added a clear NotSupported error for this case (and any other primitive types). ICollector/IAsyncCollector is not intended to support primitive types (however string and byte[] ARE supported). https://github.com/Azure/azure-webjobs-sdk/commit/e12524f9286ab53613aaf59e018444c235e9201a
