### ISSUE TITLE
Dashboard Indexing fails on Control characters

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#599]
Reported on SO [here](https://social.msdn.microsoft.com/Forums/azure/en-US/b14c9444-90d1-4f8d-9567-6a130c33a808/azure-webjobs-indexer-throws-storageexception-specified-value-has-invalid-control-characters?forum=windowsazurewebsitespreview). Still need to get a repro for this, but it is likely related to [this issue](https://github.com/Benjimawoo/azure-webjobs-sdk/commit/930e662c95d1de8f2671c08a87f9806964eab519) that we fixed a few months ago.

**Comment by j055** [comment]
I am not aware of any control chars being included. I'm using the C# Storage SDK and serializing my POCO with Newtonsoft before adding the message to the queue. It's unlikely that the values of any properties would contain control chars and even if they did I would think that the SerializeObject method would escape them. The POCO has one string, 2 ints and a Guid type. The string contains a short single line alphanumeric name.

```
var queueReference = queueClient.GetQueueReference("sms-out-message");
queueReference.AddMessage(new CloudQueueMessage(Newtonsoft.Json.JsonConvert.SerializeObject(queueInfo)));
```

**Comment by j055** [comment]
We are still having problems with the indexer. Would it help if we gave you access to our setup?
Thanks

**Comment by mathewc** [comment]
I've been meaning to get around to trying to repro this. What would really help is if you can narrow down a message that causes this. If you can do that, it would expedite things. What I need is a queue message payload that will repro this.

**Comment by j055** [comment]
The attached screenshots were grabbed at 2015-12-05T10:33. The indexing errors started at  2015-12-05T10:20:39. The second screen shot shows that there is no direct link between when functions were triggered and indexer failures occurred. I have tried but cannot produce a message to cause this.

![indexing2](https://cloud.githubusercontent.com/assets/6011428/11607402/bff12d4e-9b3c-11e5-8b35-c107d735b8ea.png)
![indexing3](https://cloud.githubusercontent.com/assets/6011428/11607401/bfee883c-9b3c-11e5-92b4-248189073877.png)

**Comment by mathewc** [comment]
Ok, here's an idea for us to get to the bottom of this together. It is very easy for you to run the Dashboard locally - instructions on how to do that can be found [here](https://github.com/Azure/azure-webjobs-sdk/wiki/Development).

Once you have it running locally, add a bit of code in **Dashboard.Data.BlobConcurrentTextStore.CreateOrUpdate** to log the full details of the metadata/text being logged. That should be enough for us to construct a repro.

**Comment by j055** [comment]
I will try to have a look at this in the next few days.

**Comment by j055** [comment]
I have not have time yet to run the dashboard locally, but I will as soon as I can. There has been a new development. At 2015-12-14T22:40:32 a new error appeared 'Thread was being aborted.'. 

```
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.RuntimeTypeHandle.ConstructName(RuntimeTypeHandle handle, TypeNameFormatFlags formatFlags, StringHandleOnStack retString)
   at System.RuntimeType.RuntimeTypeCache.ConstructName(String& name, TypeNameFormatFlags formatFlags)
   at System.RuntimeType.get_FullName()
   at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.CanConvert(Type objectType)
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Microsoft.Azure.WebJobs.Protocols.PolymorphicJsonConverter.NonCircularContractResolver.CreateContract(Type objectType) in c:\BuildAgent\work\1bab5238e8bc2cc\public\src\Microsoft.Azure.WebJobs.Protocols\PolymorphicJsonConverter.cs:line 250
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
   at Microsoft.Azure.WebJobs.Protocols.PolymorphicJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in c:\BuildAgent\work\1bab5238e8bc2cc\public\src\Microsoft.Azure.WebJobs.Protocols\PolymorphicJsonConverter.cs:line 135
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Dashboard.Data.JsonVersionedDocumentStore`1.UpdateOrCreateIfLatest(String id, DateTimeOffset targetVersion, IDictionary`2 otherMetadata, TDocument document, String currentETag, DateTimeOffset currentVersion) in c:\BuildAgent\work\1bab5238e8bc2cc\public\src\Dashboard\Data\JsonVersionedDocumentStore.cs:line 69
   at Dashboard.Data.FunctionIndexManager.UpdateOrCreateIfLatest(FunctionSnapshot snapshot, String currentETag, DateTimeOffset currentVersion) in c:\BuildAgent\work\1bab5238e8bc2cc\public\src\Dashboard\Data\FunctionIndexManager.cs:line 49
   at Dashboard.Indexers.HostIndexer.ProcessHostStarted(HostStartedMessage message) in c:\BuildAgent\work\1bab5238e8bc2cc\public\src\Dashboard\Indexers\HostIndexer.cs:line 89
   at Dashboard.Indexers.Indexer.UpdateCore() in c:\BuildAgent\work\1bab5238e8bc2cc\public\src\Dashboard\Indexers\Indexer.cs:line 67
   at Dashboard.Indexers.Indexer.Update() in c:\BuildAgent\work\1bab5238e8bc2cc\public\src\Dashboard\Indexers\Indexer.cs:line 35
```

The dashboard has stopped working completely. There's a message 'No functions are present.' and no new invocations have been added to the log. The webjob application is still working correctly.

**Comment by j055** [comment]
I found that the application was using about 25m per hour of CPU. After I deleted the azure-* blob containers it immediately went down to a few seconds. Any ideas why that would be the case?

**Comment by mathewc** [comment]
The issues might be reated - i.e, if the Dashboard indexer is choking on control characters and failing repeatedly during indexing. I'd like to resolve the first issue first then see if the second issue persists.

**Comment by j055** [comment]
Having trouble with strong name skip verification. This is the entry:

```
Assembly/Strong Name                  Users
===========================================
*,31bf3856ad364e35                    All users
```

Get 'Strong name signature could not be verified' when I view in the browser.

**Comment by mathewc** [comment]
Hmmm, this works for other people (e.g. this [SO post](http://stackoverflow.com/questions/30901021/view-local-azure-webjobs-sdk-dashboard-for-debugging-webjobs-sdk-console-process)). Perhaps you need to retart VS/Browser after adding the skip entries?

**Comment by j055** [comment]
OK, you were right! I have it running locally now and have added tracing to the method you suggested. Of course, now for the first time since I reported the problem and after I cleared the blob containers again, I don't have any errors, locally or in the app. In fact, at the moment, everything is working perfectly. I guess you want me to wait for an error and then try to trace it out with the local version?

**Comment by mathewc** [comment]
Awesome, thanks for your help. Yes we basically just want to capture all the details possible about the message payload that causes this error for you so we can debug/fix. I'm hoping you'll be able to dump the full message contents when it happens allowing us to have a repro. Thanks :)

**Comment by mathewc** [comment]
Any news on this? Have you captured a repro?

**Comment by j055** [comment]
No indexing errors. I think we need another week to know if it's going to break or not. The site will get busier now the new year has started.

**Comment by j055** [comment]
I think it's a right single quotation mark:

![quote](https://cloud.githubusercontent.com/assets/6011428/12358034/34746d12-bba3-11e5-80bc-854dc648763b.png)

**Comment by mathewc** [comment]
Thanks for digging in. I'll try to repro with this and let you know. If this is it, we should be able to roll out a fix quickly, thanks.

**Comment by mathewc** [comment]
Hmmm, I tried using a queue message like yours above, and my Dashboard was able to index the invocation just fine. I tried with a message like "{ "Name": "Bishop's Hat" }". Are you saying that the queue message from the image above reliably reproduces the issue?

**Comment by j055** [comment]
Your example looks like it contains a single quote ASCII (39), whereas I believe the error is caused using a right single quotation ASCII (8217).

**Comment by mathewc** [comment]
Thanks. I tried that as well, and it is indexed properly as well.

![capture](https://cloud.githubusercontent.com/assets/1056548/12761628/8def2d68-c9a0-11e5-922c-230654df1eb1.PNG)

**Comment by christopheranderson** [comment]
No repro. Please reply if we've seen this again.
