### ISSUE TITLE
Worker Role using WebJob SDK is shutting down

### ISSUE THREAD

**Issue by rohankulkarni21** [Azure/azure-webjobs-sdk#627]
Hi

I am using WebJobs SDK 1.1.1 and WindowsAzure.Storage 5.0.2 in a Worker Role where QueueTrigger function is written which take a message from queue and does a long running process.

My worker role was running fine earlier but now there are about 200000 message in the queue.
I am into UAT and my worker role is shutting down with the following error:
It is a show stopper for us. please help

An unhandled exception occurred. Type: Microsoft.WindowsAzure.Storage.StorageException Process ID: 14552
Process Name: WaWorkerHost
Thread ID: 532
AppDomain Unhandled Exception for role deployment28(71).CE.AO.Analytics.CalculationCSvc.CE.AO.Analytics.CalculationWorker_IN_0
Exception: The client could not finish the operation within specified timeout.
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsyncT
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.b__3(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.WebJobs.Host.Queues.Listeners.UpdateQueueMessageVisibilityCommand.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.b__0()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

Inner Exception: The client could not finish the operation within specified timeout.

**Comment by mathewc** [comment]
Did you recently upgrade your Azure Storage SDK version to 5.0.2? Note that the target version for the WebJobs SDK is 4.3. Generally we recommend people using that version with the SDK until we roll out a new major version update that moves us to 6.x.

Our Nuget package dependencies DO include 5.0.2 in the allowed range, and we've run our e2e tests against that version successfully, however we still ship with version 4.3 and that version receives the most testing.

One option is for you to see if this is a Storage SDK version issue by reverting back to 4.3.

**Comment by christopheranderson** [comment]
Closing this because we haven't had activity on it. Feel free to comment and we'll reopen.
