### ISSUE TITLE
JobHost.CallAsync throws FunctionInvocationException when called with a method that returns simple Task object

### ISSUE THREAD

**Issue by gibwar** [Azure/azure-webjobs-sdk#660]
#### Description
There is a bug when using `JobHost.CallAsync` to coordinate parallel executions with a method that returns a standard `Task` that was not generated by C#'s compiler's automatic output associated with an `async` method. The included sample is incredibly simple and demonstrates the problem encountered, however the actual problem was stumbled upon in a larger, more complex job. While the demonstration uses `Task.Delay`, the problem was originally occurred when a launcher function was launching multiple functions to run in parallel and used `Task.WhenAll` to return a task to complete when all other functions completed.

#### Example
```cs
namespace TestWebJob {
    using System.IO;
    using System.Threading.Tasks;
    using Microsoft.Azure.WebJobs;

    public class Program {
        static void Main()
        {
            var host = new JobHost();
            host.CallAsync(typeof(Program).GetMethod(nameof(Program.WorksAsExpected))).Wait();
            host.CallAsync(typeof(Program).GetMethod(nameof(Program.ThrowsAnException))).Wait();
        }

        [NoAutomaticTrigger]
        public static async Task WorksAsExpected(TextWriter log)
        {
            await log.WriteLineAsync("This works as expected.");
            await Task.Delay(5000);
        }

        [NoAutomaticTrigger]
        public static Task ThrowsAnException(TextWriter log)
        {
            log.WriteLine("This will throw an exception when it returns.");
            return Task.Delay(5000);
        }
    }
}
```

#### Output (with exception information):
```text
Found the following functions:
TestWebJob.Program.WorksAsExpected
TestWebJob.Program.ThrowsAnException
Executing: 'Program.WorksAsExpected' - Reason: 'This function was programmatically called via the host APIs.'
Executed: 'Program.WorksAsExpected' (Succeeded)
Executing: 'Program.ThrowsAnException' - Reason: 'This function was programmatically called via the host APIs.'
  Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '42cf5cc1-6189-4ab5-8e2d-8997970b8c31'
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Program.ThrowsAnException ---> System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at Microsoft.Azure.WebJobs.Host.Executors.TaskMethodInvoker`1.GetTaskInnerTypeOrNull(Type taskType)
   at Microsoft.Azure.WebJobs.Host.Executors.TaskMethodInvoker`1.ThrowIfWrappedTaskInstance(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.TaskMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__1.MoveNext()
```
#### Versions
I am using .Net Framework 4.6 (since 4.6.1 isn't available on Azure yet) on Visual Studio 2015 Update 1 Community Edition with the following NuGet packages:

NuGet Package | Version
-----------------|-------------
Microsoft.Azure.KeyVault.Core | 1.0.0
Microsoft.Azure.WebJobs | 1.1.1
Microsoft.Azure.WebJobs.Code | 1.1.1
Microsoft.Data.Edm | 5.7.0
Microsoft.Data.OData | 5.7.0
Microsoft.Data.Services.Client | 5.7.0
Microsoft.WindowsAzure.ConfigurationManager | 3.2.1
Newtonsoft.Json | 8.0.3
System.Spatial | 5.7.0
WindowsAzure.Storage | 5.0.2

#### Extra Detail
I was able to confirm that within the state machine generated by C#'s compiler when encountering an `async` method returns task of `Task<VoidTaskResult>` which is a generic type. However, when using a "fast path" or aggregate function such as `Task.WhenAll`, these return a `Task` with no generic parameters, causing the exception above.

#### Work around
This issue can currently be worked around by marking the called method as `async` and making sure to `await` at least one call, so the C# compiler generates the proper state machine and `JobHost.CallAsync` can then run correctly.

**Comment by gibwar** [comment]
Digging through the source code, I see that there is a [fast path check][1] if the type is _exactly_ `Task`. However, it looks like the static `Task` methods return a potentially nested type. Here's some output from C# interactive:

```text
Microsoft (R) Visual C# Interactive Compiler version 1.1.0.51109
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> Task.Delay(1300).GetType().FullName
"System.Threading.Tasks.Task+DelayPromise"
> Task.Delay(1300).GetType() == typeof(Task)
false
> Task.WhenAll(Task.Delay(1300)).GetType().FullName
"System.Threading.Tasks.Task+WhenAllPromise"
> Task.WhenAll(Task.Delay(1300)).GetType() == typeof(Task)
false
>
```

[1]: https://github.com/Azure/azure-webjobs-sdk/blob/cfc875a7f00e595410c0603e6ca65537025490a9/src/Microsoft.Azure.WebJobs.Host/Executors/TaskMethodInvoker.cs#L50 "TaskMethodInvoker.cs"
