### ISSUE TITLE
Unit tests are failing after upgrading to v2 alpha

### ISSUE THREAD

**Issue by xt0rted** [Azure/azure-webjobs-sdk#718]
I upgraded my webjobs sdk to `2.0.0-alpha-10313` so I could test the functionality added in #705 

Locally everything works fine. My webjobs are trigged (queue triggers), I can update my storage resources, and my unit tests which run against the storage emulator all pass as well.

Once moving this up to AppVeyor my unit tests that hit the storage emulator are all failing. I'm not sure why this is since nothing has changed aside from the `Microsoft.Azure.WebJobs` NuGet package and it all runs fine locally.

The only other update was [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/7.0.0) which went from `5.0.2` to `7.0.0` because of the dependency update.

In my AppVeyor.yml I'm starting the emulator like so:
```shell
"C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
Windows Azure Storage Emulator 4.2.0.0 command line tool
The storage emulator was successfully started.
"C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" status
Windows Azure Storage Emulator 4.2.0.0 command line tool
IsRunning: True
BlobEndpoint: http://127.0.0.1:10000/
QueueEndpoint: http://127.0.0.1:10001/
TableEndpoint: http://127.0.0.1:10002/
```

My app.config contains the following connection strings:
```xml
<connectionStrings>
    <add name="AzureWebJobsDashboard" connectionString="UseDevelopmentStorage=true;" />
    <add name="AzureWebJobsStorage" connectionString="UseDevelopmentStorage=true;" />
    <add name="StorageConnectionString" connectionString="UseDevelopmentStorage=true;" />
</connectionStrings>
```

The error I'm getting is:
```
Microsoft.WindowsAzure.Storage.StorageException : The remote server returned an error: (400) Bad Request.
  ----> System.Net.WebException : The remote server returned an error: (400) Bad Request.

   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.EndCreateIfNotExists(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 381
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Eei.Library.Storage.Tests.AzureBlobStorageContainerTests.<RetrieveAsync_Should_Get_The_Stream_Contents_From_Azure>d__1.MoveNext() in C:\projects\eei\test\Library.Tests\Storage\Tests\AzureBlobStorageContainerTests.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
--WebException
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.<ExistsImpl>b__34(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 2620
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 303
```

**Comment by mathewc** [comment]
Try moving to the latest storage emulator (version 4.3). That's what I installed when I tested things.

**Comment by xt0rted** [comment]
Installing v4.3 on the build server fixed the problem.
