### ISSUE TITLE
ServiceBusTrigger doesn't support topic's connection string, requires root's instead

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#749]
I have the following ServiceBus trigger in my function:

``` csharp
public async Task SaveInvoice(
    [ServiceBusTrigger("mytopic", "mysub", AccessRights.Listen)] BrokeredMessage message,
    TextWriter log)
{
}
```

Connection string is like this:

> Endpoint=sb://mysb.servicebus.windows.net/;SharedAccessKeyName=receiver;SharedAccessKey=mykey

But this is the root's connection string for role 'receiver`.

When I use mytopic's connection string for role 'receiver` I'm getting an error:

```
An unhandled exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.dll

Additional information: 40103: Invalid authorization token signature, Resource: sb://mysb.servicebus.windows.net/mytopic/subscriptions/mysub. TrackingId: 6394d4e1-5535-4ce3-962e-72fd7feeb849_G40, Timestamp:6/17/2016 6:36:59 PM

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.ReceiveAsyncResult.<GetAsyncSteps>b__26(ReceiveAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.<GetAsyncSteps>b__86(RetryReceiveAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.OpenOnceManager.OpenOnceManagerAsyncResult`1.OperationComplete(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndReceive(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump.StartAsyncResult.<GetAsyncSteps>b__12(StartAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.RunSynchronously()
   at Microsoft.ServiceBus.Messaging.MessageReceiver.OnMessage(MessageReceivePump pump)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.<StartAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.HeartbeatListener.<StartAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.<StartAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.Start()
   at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
   at Microsoft.Incentives.Partner.PaymentRequest.Api.WebJobs.Program.Main() in D:\Projects\PaymentRequest\Api.WebJobs\Program.cs:line 11
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I can share detailed credentials, ping alexbat@msft.

**Comment by abatishchev** [comment]
hi Christopher, how do you think is there a chance it will be fixed in 2.0.0?

**Comment by christopheranderson** [comment]
For the 2.0.0 full release? Probably. We're not going to do this in the closest release, though.

**Comment by abatishchev** [comment]
Can you please share some more on the upcoming release? Would it be a maintenance release for the 1.x branch?

**Comment by mathewc** [comment]
No, the next release is the big 2.0 release where we're moving to the latest Azure Storage and all our other dependencies and adding a bunch of new stuff. It may take us a while to land, but we're actively working on it.

We'd only do a maintenance release on the 1.x train for a hotfix or serious issue at this point.

**Comment by abatishchev** [comment]
hi @mathewc, do you know whether this was resolved in 2.0?

**Comment by abatishchev** [comment]
hi, any news on this by chance, please?

**Comment by abatishchev** [comment]
Any chance to address this in 3.x (if not addressed yet)?

**Comment by mathewc** [comment]
You are using using a topic subscription, with a connection string without Manager rights?

**Comment by JaDevGuy** [comment]
Correct. Using a topic subscription and a connection string with only Listen rights once I specify the AccessRights to Listen.

`public void ProcessQueueMessage([ServiceBusTrigger(topicName: "topic1", subscriptionName:"topic1subscription", access: AccessRights.Listen, Connection = "AzureWebJobsServiceBusTopic")] BrokeredMessage message, 
                                        TextWriter log)`

**Comment by mathewc** [comment]
Thanks for confirming - that's what I suspected. Closing this as I believe it has been addressed.
