### ISSUE TITLE
NullReference exception when running a Console App (with WebJob SDK 2.0.0-alpha-10349 bits) locally and disconnected from Azure Storage

### ISSUE THREAD

**Issue by CarlosSardo** [Azure/azure-webjobs-sdk#754]
Hi Guys,

I get a NullReferenceException when running a Console App (with WebJob SDK 2.0.0-alpha-10349 bits) locally and disconnected from Azure Storage.

```
        JobHostConfiguration config = new JobHostConfiguration();
        config.HostId = Guid.NewGuid().ToString("n");
        config.DashboardConnectionString = null;
        config.StorageConnectionString = null;
        config.UseTimers();

        JobHost host = new JobHost(config);
        host.RunAndBlock();
```

I have a Functions.cs with the following:

```
    public static void TimerJob([TimerTrigger("00:00:05")] TimerInfo timerInfo,
                                TextWriter log)
    {
        log.WriteLine("Scheduled job fired!");
    }
```

From some of the comments I read in this pull request (PR) here (https://github.com/Azure/azure-webjobs-sdk/pull/639), I guess you saw it comming.

Any thoughts on how to deal with this? I have some ideas and I would be glad to contribute with a proper fix + PR.

Cheers,
Carlos Sardo

**Comment by davidebbo** [comment]
Can you share the Exception's full stack? Thanks!

**Comment by mathewc** [comment]
TimerTrigger requires a storage account to operate (it stores schedule information and singleton lock info in blob storage). While the null ref exception you mention might not be proper error handling (we can fix), I don't expect what you're trying to do above to work.

**Comment by CarlosSardo** [comment]
@davidebbo Here it is:

`System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Azure.WebJobs.Host
  StackTrace:
       at Microsoft.Azure.WebJobs.Host.SingletonManager.GetLockDirectory(String accountName)
       at Microsoft.Azure.WebJobs.Host.SingletonManager.<TryLockAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.<StartAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.<StartAsyncCore>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.<StartAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.JobHost.Start()
       at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
       at WJConsoleApp.Program.Main(String[] args) in C:\Projects\Samples\WJConsoleApp\WJConsoleApp\Program.cs:line 25
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
`

**Comment by davidebbo** [comment]
@mathewc we should probably at least add error handling in `SingletonManager.GetLockDirectory` so it doesn't blow up.

**Comment by mathewc** [comment]
The issue is that until very recently ([this commit](https://github.com/Azure/azure-webjobs-sdk/commit/3994da6e88922a02fbfc39b955767dad1c509896) for Azure Functions) we **required** a storage account, so the system expects one everywhere and assumes it w/o guards. We made that change to allow running with no storage account configured, and we discussed the fact that when doing so, we knew things would blow up if you tried to use any storage features.

We're not going to go sprinkle guards throughout the code. We could investigate whether there are some centralized checks we could put in place. That work really should have been done in the above commit.

**Comment by CarlosSardo** [comment]
@davidebbo & @mathewc : improved error handling and centralized are good idea. Although, there would still be problems regarding the requirements for Singleton or TimerTrigger features to work (i.e.: blob leases). Right?

**Comment by GiancarloLelli** [comment]
Hello @davidebbo - is this issue still "up-for-grabs"? I think I can help :)

**Comment by davidebbo** [comment]
Thanks for your offer to help! I'm no longer working on Functions, so I'll let @mathewc or others comment further.

**Comment by mathewc** [comment]
This is a really old issue against the 2.0.0-alpha prerelease. SDK is now at 2.3.0. I don't think this is an issue anymore for 2.3.0. For v3 (3.0.3) the startup model has completely changed (.NET Core) and again, I don't think we have this issue anymore.

If it turns out this is still an issue we can reopen.
