### ISSUE TITLE
getting Newtonsoft-joson exception when using Azure-web-job sdk.

### ISSUE THREAD

**Issue by arbarik** [Azure/azure-webjobs-sdk#780]
Hi,

I am using visual studio to develop the Azure web job. I have added Azure web jobs library by nugget.
 
Microsoft.Azure.WebJobs : version  1.1.2.0
Microsoft.Azure.WebJobs.Host : version 1.1.2.0
Microsoft.WindowsAzure.Storage: version 7.1.2.0

Also I need some json manipulation in my web job, so I have added newtonsoft.json 9.0.0.0 version. 
When webjob starts up, It throws below exception.
Please help me to resolve this. I can't add any library manually. it should be through nugget, as we have CI and build automation in place. 

`2016-07-29T17:38:13  PID[11260] Error       Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
2016-07-29T17:38:13  PID[11260] Error          at Microsoft.Azure.WebJobs.Host.Protocols.PersistentQueueWriter`1.<EnqueueAsync>d__0.MoveNext()
2016-07-29T17:38:13  PID[11260] Error          at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
2016-07-29T17:38:13  PID[11260] Error          at Microsoft.Azure.WebJobs.Host.Protocols.PersistentQueueWriter`1.EnqueueAsync(T message, CancellationToken cancellationToken)
2016-07-29T17:38:13  PID[11260] Error          at Microsoft.Azure.WebJobs.Host.Loggers.PersistentQueueLogger.LogHostStartedAsync(HostStartedMessage message, CancellationToken cancellationToken)
2016-07-29T17:38:13  PID[11260] Error          at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.LogHostStartedAsync(IFunctionIndex functionIndex, HostOutputMessage hostOutputMessage, IHostInstanceLogger logger, CancellationToken cancellationToken)
2016-07-29T17:38:13  PID[11260] Error          at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__b.MoveNext()
2016-07-29T17:38:13  PID[11260] Error       --- End of stack trace from previous location where exception was thrown ---
2016-07-29T17:38:13  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-07-29T17:38:13  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2016-07-29T17:38:13  PID[11260] Error          at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__0.MoveNext()
2016-07-29T17:38:13  PID[11260] Error       --- End of stack trace from previous location where exception was thrown ---
2016-07-29T17:38:13  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-07-29T17:38:13  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2016-07-29T17:38:13  PID[11260] Error          at Microsoft.Azure.WebJobs.JobHost.<CreateContextAndLogHostStartedAsync>d__f.MoveNext()
2016-07-29T17:38:13  PID[11260] Error       --- End of stack trace from previous location where exception was thrown ---
2016-07-29T17:38:13  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-07-29T17:38:14  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2016-07-29T17:38:14  PID[11260] Error          at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__0.MoveNext()
2016-07-29T17:38:14  PID[11260] Error       --- End of stack trace from previous location where exception was thrown ---
2016-07-29T17:38:14  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-07-29T17:38:14  PID[11260] Error          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2016-07-29T17:38:14  PID[11260] Error          at Microsoft.Azure.WebJobs.JobHost.Start()
2016-07-29T17:38:14  PID[11260] Error          at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()`

**Comment by christopheranderson** [comment]
This was a regression on Azure App Service. It has been fixed.
