### ISSUE TITLE
Queue Listener being triggered instead of Bloblistener

### ISSUE THREAD

**Issue by sharjeel-ahmed** [Azure/azure-webjobs-sdk#796]
For some weird reason Queue listener is being triggered instead of blob listener and hence it is failing.
I am using SouthEast Asia servers for everything.

I am using Blobs and Blobtriggers only. No queues. 
I am trying to debug the source code to zero in on the problem. 

 `[08/23/2016 12:01:11 > e28089: ERR ] Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote name could not be resolved: 'trakdstorage.queue.core.windows.net' ---> System.Net.WebException: The remote name could not be resolved: 'trakdstorage.queue.core.windows.net'
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
[08/23/2016 12:01:11 > e28089: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
[08/23/2016 12:01:11 > e28089: ERR ]    --- End of inner exception stack trace ---
[08/23/2016 12:01:11 > e28089: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
[08/23/2016 12:01:11 > e28089: ERR ]    at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.EndExists(IAsyncResult asyncResult)
[08/23/2016 12:01:11 > e28089: ERR ]    at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass11.<CreateCallback>b__0(IAsyncResult ar)
[08/23/2016 12:01:11 > e28089: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/23/2016 12:01:11 > e28089: ERR ]    at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.<ExecuteAsync>d__4.MoveNext()
[08/23/2016 12:01:11 > e28089: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/23/2016 12:01:11 > e28089: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext()
[08/23/2016 12:01:11 > e28089: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/23/2016 12:01:11 > e28089: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[08/23/2016 12:01:11 > e28089: ERR ]    at System.Threading.ThreadHelper.ThreadStart()
[08/23/2016 12:01:11 > e28089: SYS ERR ] Job failed due to exit code -532462766`

Here we see clearly that Queues are getting triggered and also the URL which it is trying to access is "trakdstorage.queue.core.windows.net" instead of "trakdstorage.blob.core.windows.net"

Wanted to let the developers know about this bug.

**Comment by mathewc** [comment]
That is actually the way BlobTrigger works under the cover. We have a discovery process that discovers new/updated blobs and we put those into a queue for scale out processing. Host instances are all listening on the same queue to get blobs to process.

So that isn't your issue.

**Comment by sharjeel-ahmed** [comment]
But then trakdstorage.queue.core.windows.net does not exist and it tries to access it? or does it get created when i create a blob? I am confused now.

**Comment by mathewc** [comment]
Yes, we create all of that for you under the covers. We require a full storage account, not a blob only storage account. What kind of account are you trying to use? That might be the issue - we can't create the control queue we need.

**Comment by sharjeel-ahmed** [comment]
Yes looks like I have a Blob storage account. Bummer!! I guess this needs to be documented then that it works only with a General Purpose Storage not a blob only storage. 

I know this is not exactly a support section, but is there anyway I can use another general purpose storage account for all the background work(which is done by you) and continue using this blob account for the main upload? At this moment I cannot afford to create another storage account for blob as most of my apps/webapps have been configured to use this one.

**Comment by mathewc** [comment]
Yes, we've had others run into this issue, so I do agree we need to document this or even better, find a way to throw an error if the wrong account type is used. Here's a related issue: https://github.com/Azure/azure-webjobs-sdk/issues/710.

Yes, you can use `StorageAccountAttribute` to indicate which storage account to use for various bindings. More details on that in the release notes here https://github.com/Azure/azure-webjobs-sdk/wiki/Release-Notes.

**Comment by mathewc** [comment]
I created an issue https://github.com/Azure/azure-webjobs-sdk/issues/797 to track inprovements here, thanks.

**Comment by TimoRiikonen** [comment]
This issue appears to be a problem still I presume.
I make **PowerScript** command 
$al = Set-SPOMigrationPackageAzureSource -SourceFilesPath $LocalFileShare -SourcePackagePath C:\temp\SPO_Package\ -AzureQueueName migrationqueue -AccountName $AccountName -AccountKey $AccountKey

And it gives me the error
Set-SPOMigrationPackageAzureSource : The remote name could not be resolved: 'casem.queue.core.windows.net'
At C:\Users\fitimriik\Documents\Sharepoint\Scripts\SyncSp4.ps1:151 char:7
+ $al = Set-SPOMigrationPackageAzureSource -SourceFilesPath $LocalFileS ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOMigrationPackageAzureSource], StorageException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Storage.StorageException,Microsoft.Online.SharePoint.PowerShell.CopyMigrationPackage

Btw, notice how it ignores the queue name I submitted (it doesn't work without that either).
Hints in here tell that General Purpose Storage should work, but I don't get this to work with that or with blob storage either.

I have created blob storage in four different ways, but I haven't succeeded yet with getting everything to go correctly. 
Could you tell me how to create the queue manually as I am not using the SDK?
Or do I have a different problem that just sounds identical with this SDK problem?
