### ISSUE TITLE
Handle large log output 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#863]
With the Fast Logger (Which gets used by Functions), Logging output is truncated. But excpetion.ToSTring() can quickly blow this limit.  Allow larger output logging and improve this experience.

**Comment by christopheranderson** [comment]
Is this something that needs prioritizing, Mike?

**Comment by lindydonna** [comment]
@MikeStall What is the priority on this?

**Comment by christopheranderson** [comment]
**Notes from triage:**
When a Function fails, we capture their log output; that hits our truncation problem.
Would be good to fix, would be good to use append blob. Would be good to show an error balloon in portal (filed an issue).

**Comment by scottmcm** [comment]
I got the following in the "Logs" box on the portal today:
```
...obs.Script.Description.FunctionInvokerBase.<Invoke>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__3b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__1a.MoveNext()
   --- End of inner exception stack trace ---
```

Is that this truncation issue?  Without any message or anything from my code, there's not much I can do with it.

(To be explicit: The "..." at the beginning is exactly what was in the <textarea>, not be eliding something.)

**Comment by paulbatum** [comment]
Not as much as a concern anymore as functions is switching to app insights as the default monitoring experience. However there are still functions scenarios where this logging will be used (on prem, for example).
