### ISSUE TITLE
[Question] WebJobs .NetCore

### ISSUE THREAD

**Issue by XcoderTeam** [Azure/azure-webjobs-sdk#926]
Hi,

When upload the binary zip to the web jobs, and run it showing this error.
1. How to solved this below issue?

> [11/29/2016 14:58:55 > c230b8: SYS INFO] Status changed to Initializing
[11/29/2016 14:58:55 > c230b8: SYS INFO] Job directory change detected: Job file 'Job.Feed\settings.job' has been deleted.
[11/29/2016 14:58:57 > c230b8: SYS INFO] Run script 'project.json' with script host - 'DnxScriptHost'
[11/29/2016 14:58:57 > c230b8: SYS INFO] Status changed to Running
[11/29/2016 14:58:59 > c230b8: INFO] Determining latest version
[11/29/2016 14:59:00 > c230b8: INFO] 'dnx-clr-win-x86.1.0.0-rc1-update2' is already installed in D:\local\UserProfile\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2.
[11/29/2016 14:59:00 > c230b8: INFO] Adding D:\local\UserProfile\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin to process PATH
[11/29/2016 14:59:00 > c230b8: INFO] Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16609
[11/29/2016 14:59:00 > c230b8: INFO] 
[11/29/2016 14:59:00 > c230b8: INFO]   CACHE https://api.nuget.org/v3/index.json
[11/29/2016 14:59:00 > c230b8: INFO] Restoring packages for D:\local\Temp\jobs\triggered\JobFeedIndeed\0dsu0nw3.4mn\Job.Feed\project.json
[11/29/2016 14:59:00 > c230b8: INFO] ----------
[11/29/2016 14:59:00 > c230b8: INFO] D:\local\Temp\jobs\triggered\JobFeedIndeed\0dsu0nw3.4mn\Job.Feed\project.json(0,0): Error: Microsoft.Dnx.Runtime.FileFormatException: unknown keyword platform ---> System.InvalidOperationException: unknown keyword platform
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Runtime.LibraryDependencyType.Parse(String keyword)
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Runtime.ProjectReader.PopulateDependencies(String projectPath, IList`1 results, JsonObject settings, String propertyName, Boolean isGacOrFrameworkReference)
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Runtime.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics)
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
[11/29/2016 14:59:00 > c230b8: INFO]    --- End of inner exception stack trace ---
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
[11/29/2016 14:59:00 > c230b8: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/29/2016 14:59:00 > c230b8: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/29/2016 14:59:00 > c230b8: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
[11/29/2016 14:59:00 > c230b8: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/29/2016 14:59:00 > c230b8: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[11/29/2016 14:59:00 > c230b8: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/29/2016 14:59:00 > c230b8: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[11/29/2016 14:59:00 > c230b8: INFO]    at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
[11/29/2016 14:59:00 > c230b8: INFO] ----------
[11/29/2016 14:59:00 > c230b8: INFO] Restore failed
[11/29/2016 14:59:00 > c230b8: INFO] unknown keyword platform
[11/29/2016 14:59:00 > c230b8: INFO] 
[11/29/2016 14:59:00 > c230b8: INFO] Feeds used:
[11/29/2016 14:59:00 > c230b8: INFO]     https://api.nuget.org/v3-flatcontainer/
[11/29/2016 14:59:00 > c230b8: INFO] An error has occurred during running DNX WebJob.
[11/29/2016 14:59:00 > c230b8: SYS INFO] Status changed to Failed
[11/29/2016 14:59:00 > c230b8: SYS ERR ] Job failed due to exit code 255

2. How to parse the argument to the web jobs?

**Comment by christopheranderson** [comment]
Are you using the WebJobs SDK, or is this just a DNX console app? This is the wrong forum for DNX console app WebJobs issues. I'd ask on our Forums - https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview&filter=alltypes&sort=lastpostdesc
