### ISSUE TITLE
Null ref on storage account type validation codepath

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk#927]
Customer reported an issue where their function was failing to be indexed due to a null ref exception. This is the stack trace:

```
2016-11-30T05:02:38.455 Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.CreateREMOVED' ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Host.Storage.StorageAccountExtensions.AssertTypeOneOf(IStorageAccount account, StorageAccountType[] types)
   at Microsoft.Azure.WebJobs.Host.Tables.TableAttributeBindingProvider.<TryCreateAsync>d__1d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Bindings.GenericCompositeBindingProvider`1.<TryCreateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Bindings.CompositeBindingProvider.<TryCreateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__0.MoveNext()
```

It looks like the specific issue is that this method and its callers don't handle a null storage account:
https://github.com/Azure/azure-webjobs-sdk/blob/663a508e8a851629c26a51e7de3af36629dfd120/src/Microsoft.Azure.WebJobs.Host/Storage/IStorageAccountExtensions.cs

**Comment by SimonLuckenuik** [comment]
To add information, the "connection" part of the binding was set to a value, but there was no matching key (typo) in the appSettings.

**Comment by davidebbo** [comment]
This also just came up on https://social.msdn.microsoft.com/Forums/en-US/cd874148-d15b-4dad-a0d5-b2521c00a5f6/error-indexing-method?forum=AzureFunctions

**Comment by soninaren** [comment]
Fixed in https://github.com/Azure/azure-webjobs-sdk/pull/946

**Comment by soninaren** [comment]
Further fixes in
https://github.com/Azure/azure-webjobs-sdk/pull/961
