### ISSUE TITLE
BlobTrigger based webjobs failing due entries in logs

### ISSUE THREAD

**Issue by PrzemekGawron** [Azure/azure-webjobs-sdk#951]
We experience a serious production issue that makes all webjobs that are using BlobTrigger unusable.
They continuously restarting each time throwing following error:

```
[12/21/2016 10:11:26 > 5053fb: ERR ] Unhandled Exception: System.FormatException: Failed to parse RequestedObjectKey property of the log entry. It should be in one of the supported formats: "https://account.blob.core.windows.net/container/blob", or"/account/container/blob"
[12/21/2016 10:11:26 > 5053fb: ERR ]    at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.StorageAnalyticsLogEntry.ToBlobPath()
[12/21/2016 10:11:26 > 5053fb: ERR ]    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
[12/21/2016 10:11:26 > 5053fb: ERR ]    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
[12/21/2016 10:11:26 > 5053fb: ERR ]    at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobLogListener.<GetRecentBlobWritesAsync>d__9.MoveNext()
[12/21/2016 10:11:26 > 5053fb: ERR ] --- End of stack trace from previous location where exception was thrown ---
[12/21/2016 10:11:27 > 5053fb: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[12/21/2016 10:11:27 > 5053fb: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/21/2016 10:11:27 > 5053fb: ERR ]    at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.PollLogsStrategy.<ExecuteAsync>d__6.MoveNext()
[12/21/2016 10:11:28 > 5053fb: ERR ] --- End of stack trace from previous location where exception was thrown ---
[12/21/2016 10:11:28 > 5053fb: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[12/21/2016 10:11:28 > 5053fb: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/21/2016 10:11:28 > 5053fb: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext()
[12/21/2016 10:11:28 > 5053fb: ERR ] --- End of stack trace from previous location where exception was thrown ---
[12/21/2016 10:11:28 > 5053fb: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
[12/21/2016 10:11:28 > 5053fb: ERR ]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[12/21/2016 10:11:28 > 5053fb: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[12/21/2016 10:11:28 > 5053fb: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[12/21/2016 10:11:28 > 5053fb: ERR ]    at System.Threading.ThreadHelper.ThreadStart()
[12/21/2016 10:11:28 > 5053fb: SYS ERR ] Job failed due to exit code -532462766
[12/21/2016 10:11:28 > 5053fb: SYS INFO] Process went down, waiting for 60 seconds
[12/21/2016 10:11:28 > 5053fb: SYS INFO] Status changed to PendingRestart`
```

After analysis it appeared the problem is occurring because of log entries like this:

`1.0;2016-12-21T12:04:39.2441654Z;PutBlob;ThrottlingError;503;0;0;authenticated;some;someor;blob;"https://some.blob.core.windows.net:443/azure-webjobs-dashboard/functions/stats/azure-webjobs-host-cb64fd6cad684f45bc555f04a8b9bb05_GPSTransactionProcessor.Functions.ProcessCardFeeMessage";"/";08936f82-0001-004b-6082-5b249d000000;0;100.111.228.34:49524;2015-12-11;624;0;95;198;51;;;;;;"Azure-Storage/7.2.1 (.NET CLR 4.0.30319.42000; Win32NT 6.2.9200.0)";;"25b27839-8f4e-471f-9cdc-f7a0a478e3c2"`

This CSV line at column 11 contain character '/' which is not expected.

The workaround is to remove invalid logs and wait until they appear again. But it is only temporary and NOT acceptable on production.

Version: Azure-Storage/7.2.1

**Comment by mathewc** [comment]
What version of the WebJobs SDK are you using?

**Comment by PrzemekGawron** [comment]
7.2.1

21.12.2016 6:01 PM "Mathew Charles" <notifications@github.com> napisał(a):

**Comment by PrzemekGawron** [comment]
Sorry, Azure WebJobs SDK version is 1.1.2

**Comment by brettsam** [comment]
Here's where we try to parse that line: https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/StorageAnalyticsLogEntry.cs#L124

It does look like this is a bug -- we don't expect that.

@PrzemekGawron -- It looks like this log entry is for a ThrottlingError. Any idea what you were doing to get that? I'll start trying to see if I can reproduce this.
@mathewc -- Any idea if the details of these log entries is documented anywhere? We seem to be expecting very specific strings there.

**Comment by brettsam** [comment]
I'm not sure if this is new behavior or just rare -- but it looks like we even have a test to ensure we throw if we get a "/" in that spot -- https://github.com/Azure/azure-webjobs-sdk/blob/dev/test/Microsoft.Azure.WebJobs.Host.UnitTests/Blobs/Listeners/StorageAnalyticsLogEntryTests.cs#L85

It seems like we could just return null instead of throwing. The only usage of this call checks for null: https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/BlobLogListener.cs#L67-L75

It seems bad to throw exceptions there when there's not much an end-user could do about it.

**Comment by PrzemekGawron** [comment]
@brettsam -- we have a lot of webjobs that are really heavily used (most of them are processing data from queues and blob containers, the queues reach size > 100k messages). Our App Service plan is running near 100% CPU and 60% memory usage. 

Solution you proposed seems to be simple and legit. I would really appreciate quick fix for that because our production is hurting.

**Comment by mathewc** [comment]
@PrzemekGawron We'll get this in soon. Would you be able to use a prerelease version with the fix? We're currently working on the 2.0.0-beta3 release (https://github.com/Azure/azure-webjobs-sdk/releases). We'd be able to get you a version with the fix on our myget feed.

**Comment by PrzemekGawron** [comment]
@mathewc If there are no breaking changes I think I will be able to switch to beta.

**Comment by mathewc** [comment]
The 2.0.0 is a major version release, so there are breaking changes. Whether any of those would affect you is unclear, but it is a major release.

**Comment by PrzemekGawron** [comment]
I've updated to beta2 and it seems to be good: project is compiling (without any code changes) and tests are passing so I think we'll be good with beta3.

**Comment by mathewc** [comment]
Ok - for your reference you can see the release notes I linked to above which details the changes that have happened since 1.1.2 (in the beta1/beta2 releases).

**Comment by brettsam** [comment]
This fix is now available on the MyGet feed. See this to get set up: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds

[2.0.0-beta2-10491](https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs/2.0.0-beta2-10491) is the first build with the change.
